extractRequestData:
  assign:
    cookie: ${incoming.headers.cookie}
    widgetAnimation: ${incoming.body.widgetAnimation}
    widgetProactiveSeconds: ${incoming.body.widgetProactiveSeconds}
    widgetDisplayBubbleMessageSeconds: ${incoming.body.widgetDisplayBubbleMessageSeconds}
    widgetBubbleMessageText: ${incoming.body.widgetBubbleMessageText}
    widgetColor: ${incoming.body.widgetColor}
    isWidgetActive: ${incoming.body.isWidgetActive}

extractTokenData:
  call: http.post
  args:
    # TODO: replace with env variable and correct path to TIM endpoint
    url: http://ruuter-v2-private:8088/mocks/mock-tim-custom-jwt-userinfo
    headers:
      cookie: ${cookie}
    body:
      # TODO: pass cookie name correctly to TIM
      cookieName: "customJwtCookie"
  result: jwtResult

validateAdministrator:
  switch:
    # TODO: use correct structure when request is made against TIM
    - condition: ${jwtResult.response.body.response.authorities.includes("ROLE_ADMINISTRATOR")}
      next: setWidgetConfig
  next: returnUnauthorized

setWidgetConfig:
  call: http.post
  args:
    # TODO: replace with env variable
    url: http://resql:8082/set-widget-config
    body:
      widgetProactiveSeconds: ${widgetProactiveSeconds}
      widgetDisplayBubbleMessageSeconds: ${widgetDisplayBubbleMessageSeconds}
      widgetBubbleMessageText: ${widgetBubbleMessageText}
      widgetColor: ${widgetColor}
      isWidgetActive: ${isWidgetActive}
      widgetAnimation: ${widgetAnimation}
      created: ${new Date().toISOString()}
  result: setWidgetConfigResult

mapWidgetConfigData:
  call: http.post
  args:
    # TODO: replace with env variable
    url: http://dmapper:3000/json/v2/return_widget_config
    body:
      configurationArray: ${setWidgetConfigResult.response.body}
  result: widgetConfigData
  next: returnSuccess

returnSuccess:
  return: ${widgetConfigData.response.body}
  next: end

returnInvalidBody:
  return: "error: invalid body"
  next: end

returnUnauthorized:
  return: "error: unauthorized"
  next: end
