export enum AUTHORITY {
  ADMINISTRATOR = 'ROLE_ADMINISTRATOR',
  SERVICE_MANAGER = 'ROLE_SERVICE_MANAGER',
  CUSTOMER_SUPPORT_AGENT = 'ROLE_CUSTOMER_SUPPORT_AGENT',
  CHATBOT_TRAINER = 'ROLE_CHATBOT_TRAINER',
  ANALYST = 'ROLE_ANALYST',
  UNAUTHENTICATED = 'ROLE_UNAUTHENTICATED',
}
