declaration:
  call: declare
  version: 0.1
  description: "Decription placeholder for 'BOT-CONFIG'"
  method: post
  accepts: json
  returns: json
  namespace: backoffice
  allowlist:
    body:
      - field: isBotActive
        type: string
        description: "Body field 'isBotActive'"
      - field: isBurokrattActive
        type: string
        description: "Body field 'isBurokrattActive'"
      - field: isCsaNameVisible
        type: string
        description: "Body field 'isCsaNameVisible'"
      - field: isCsaTitleVisible
        type: string
        description: "Body field 'isCsaTitleVisible'"
      - field: isEditChatVisible
        type: string
        description: "Body field 'isEditChatVisible'"

extractRequestData:
  assign:
    is_bot_active: ${incoming.body.isBotActive}
    is_burokratt_active: ${incoming.body.isBurokrattActive}
    is_csa_name_visible: ${incoming.body.isCsaNameVisible}
    is_csa_title_visible: ${incoming.body.isCsaTitleVisible}
    is_edit_chat_visible: ${incoming.body.isEditChatVisible}

setBotConfig:
  call: http.post
  args:
    url: "[#CHATBOT_RESQL]/set-bot-config"
    body:
      is_bot_active: ${is_bot_active}
      is_burokratt_active: ${is_burokratt_active}
      is_csa_name_visible: ${is_csa_name_visible}
      is_csa_title_visible: ${is_csa_title_visible}
      is_edit_chat_visible: ${is_edit_chat_visible}
      created: ${new Date().toISOString()}
  result: set_bot_config_res

return_result:
  return: "Bot configurations changed successfully"
