declaration:
  call: declare
  version: 0.1
  description: "Decription placeholder for 'IS-BOT-ACTIVE'"
  method: get
  accepts: json
  returns: json
  namespace: backoffice

getConfigurationValue:
  call: http.get
  args:
    url: "[#CHATBOT_RESQL]/config/get_configuration"
    query:
      key: "is_bot_active"
  result: res

return_result:
  return: ${res.response.body[0]?.value}
  status: 200
