extractRequestData:
  assign:
    cookie: ${incoming.headers.cookie}
  next: check_if_authorized

check_if_authorized:
  template: templates/check-user-authority
  requestType: post
  headers:
    cookie: ${cookie}
  result: authority_result
  next: check_authority_result

check_authority_result:
  switch:
    - condition: ${authority_result !== "false"}
      next: getWidgetConfig
  next: returnUnauthorized

getWidgetConfig:
  call: http.post
  args:
    url: "[#CHATBOT_RESQL]:[#CHATBOT_RESQL_PORT]/get-widget-config"
  result: getWidgetConfigResult
  next: validateWidgetConfigExists

validateWidgetConfigExists:
  switch:
    - condition: "${getWidgetConfigResult.response.body.length > 0}"
      next: mapWidgetConfigData
  next: returnNotFound

mapWidgetConfigData:
  call: http.post
  args:
    url: "[#CHATBOT_DMAPPER]:[#CHATBOT_DMAPPER_PORT]/json/v2/return_widget_config"
    body:
      configurationArray: ${getWidgetConfigResult.response.body}
  result: widgetConfigData
  next: returnSuccess

returnSuccess:
  return: ${widgetConfigData.response.body}
  next: end

returnUnauthorized:
  return: "error: unauthorized"
  next: end

returnNotFound:
  return: "error: not found"
  next: end
