-- liquibase formatted sql
-- changeset Artsiom Beida:20250424093801 ignore:true
CREATE TABLE denormalized_chat (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    chat_id character varying NOT NULL,
    customer_support_id character varying,
    customer_support_display_name character varying,
    customer_support_first_name character varying,
    customer_support_last_name character varying,
    end_user_id character varying,
    end_user_first_name character varying,
    end_user_last_name character varying,
    end_user_email character varying,
    end_user_phone character varying,
    end_user_os character varying,
    end_user_url character varying,
    status character varying,
    first_message_timestamp timestamp with time zone,
    created timestamp with time zone,
    updated timestamp with time zone,
    denormalized_record_created timestamp with time zone NOT NULL DEFAULT now(),
    ended timestamp with time zone,
    forwarded_to character varying,
    forwarded_to_name character varying,
    received_from character varying,
    received_from_name character varying,
    external_id character varying,
    labels character varying [],
    comment text,
    comment_added_date timestamp with time zone,
    comment_author character varying,
    user_display_name character varying,
    user_status character varying,
    author_first_name character varying,
    author_last_name character varying,
    first_message text,
    last_message text,
    last_message_including_empty_content text,
    contacts_message text,
    last_message_timestamp timestamp with time zone,
    feedback_text text,
    feedback_rating integer,
    nps numeric,
    csa_title character varying,
    last_message_event character varying,
    last_message_event_with_content character varying,
    chat_duration_in_seconds numeric,
    is_bot boolean,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    customer_messages_count integer,
    CONSTRAINT denormalized_chat_pkey PRIMARY KEY (id)
);

CREATE INDEX idx_denorm_chat_id_updated ON public.denormalized_chat USING btree (chat_id, updated);

-- Updated INSERT script to include both IDLE and non-IDLE chats
INSERT INTO denormalized_chat (
    chat_id,
    customer_support_id,
    customer_support_display_name,
    customer_support_first_name,
    customer_support_last_name,
    end_user_id,
    end_user_first_name,
    end_user_last_name,
    end_user_email,
    end_user_phone,
    end_user_os,
    end_user_url,
    status,
    first_message_timestamp,
    created,
    updated,
    denormalized_record_created,
    ended,
    forwarded_to,
    forwarded_to_name,
    received_from,
    received_from_name,
    external_id,
    labels,
    comment,
    comment_added_date,
    comment_author,
    user_display_name,
    user_status,
    author_first_name,
    author_last_name,
    first_message,
    last_message,
    last_message_including_empty_content,
    contacts_message,
    last_message_timestamp,
    feedback_text,
    feedback_rating,
    nps,
    csa_title,
    last_message_event,
    last_message_event_with_content,
    chat_duration_in_seconds,
    is_bot,
    customer_messages_count
)
WITH combined_records AS (
    -- Including original ended chats records
    -- Chat history comment records for ended chats
    SELECT
        chc.created AS record_date,
        chc.id AS chat_history_id,
        chc.chat_id,
        chc.comment,
        chc.created AS comment_added_date,
        chc.author_display_name AS comment_author,
        m.min_id,
        m.max_id,
        m.first_message_content,
        m.max_msg_updated AS last_message_timestamp,
        m.max_msg_event AS last_message_event,
        m.max_msg_event_with_content AS last_message_event_with_content,
        m.last_message_content,
        m.last_message_including_empty_content,
        m.customer_messages_count,
        cm.contact_message_content,
        c.customer_support_id,
        m.max_msg_author_id AS author_id,
        c.customer_support_display_name,
        cu.first_name AS customer_support_first_name,
        cu.last_name AS customer_support_last_name,
        c.csa_title,
        c.end_user_id,
        c.end_user_first_name,
        c.end_user_last_name,
        c.end_user_email,
        c.end_user_phone,
        c.end_user_os,
        c.end_user_url,
        c.status,
        c.updated AS chat_updated,
        c.ended,
        c.forwarded_to,
        c.forwarded_to_name,
        c.received_from,
        c.received_from_name,
        c.external_id,
        c.labels,
        m.first_message_timestamp AS first_message_timestamp,
        c.created AS chat_created,
        c.feedback_text,
        c.feedback_rating,
        config.is_csa_title_visible,
        chc.created,
        mu.display_name AS user_display_name,
        mu.status AS user_status,
        COALESCE(m.author_first_name, mu.first_name, mu.display_name) AS author_first_name,
        COALESCE(m.author_last_name, mu.last_name) AS author_last_name,
        fsm.first_support_timestamp,
        CASE
            WHEN fsm.first_support_timestamp IS NOT NULL AND lm.last_timestamp IS NOT NULL
            THEN ABS(EXTRACT(EPOCH FROM (fsm.first_support_timestamp - lm.last_timestamp)))
            ELSE NULL
        END AS duration_seconds,
        CASE
            WHEN c.customer_support_id = bot_config.bot_institution_id THEN TRUE
            ELSE FALSE
        END AS is_bot,
        bot_config.bot_institution_id
    FROM
        chat_history_comments AS chc
    LEFT JOIN LATERAL (
        SELECT *
        FROM chat AS c
        WHERE c.base_id = chc.chat_id
        AND c.updated <= chc.created
        ORDER BY c.updated DESC
        LIMIT 1
    ) AS c ON true
    LEFT JOIN LATERAL (
        WITH content_message_bounds AS (
            SELECT
                MAX(id) AS max_content_id,
                MIN(id) AS min_content_id
            FROM message AS m
            WHERE
                m.chat_base_id = chc.chat_id
                AND m.updated <= chc.created
                AND content <> ''
                AND content <> 'message-read'
        ),
        all_message_bounds AS (
            SELECT
                MAX(id) AS max_id
            FROM message AS m
            WHERE
                m.chat_base_id = chc.chat_id
                AND m.updated <= chc.created
        ),
        customer_messages_count AS (
            SELECT COUNT(inner_m.id) AS customer_messages_count
            FROM message AS inner_m
            WHERE
                inner_m.chat_base_id = chc.chat_id
                AND inner_m.author_role = 'end-user'
                AND (inner_m.event = '' OR inner_m.event IS NULL)
                AND inner_m.updated <= chc.created
        )
        SELECT
            cmb.min_content_id AS min_id,
            cmb.max_content_id AS max_id,
            min_msg.created AS first_message_timestamp,
            min_msg.content AS first_message_content,
            max_content_msg.content AS last_message_content,
            max_msg.content AS last_message_including_empty_content,
            max_msg.updated AS max_msg_updated,
            max_msg.event AS max_msg_event,
            max_content_msg.event AS max_msg_event_with_content,
            max_msg.author_id AS max_msg_author_id,
            max_msg.author_first_name AS author_first_name,
            max_msg.author_last_name AS author_last_name,
            cmc.customer_messages_count
        FROM content_message_bounds AS cmb
        CROSS JOIN all_message_bounds AS amb
        CROSS JOIN customer_messages_count AS cmc
        LEFT JOIN message AS min_msg ON min_msg.id = cmb.min_content_id
        LEFT JOIN message AS max_content_msg ON max_content_msg.id = cmb.max_content_id
        LEFT JOIN message AS max_msg ON max_msg.id = amb.max_id
    ) AS m ON TRUE
    LEFT JOIN LATERAL (
        SELECT
            m.content AS contact_message_content
        FROM message AS m
        WHERE m.chat_base_id = chc.chat_id
        AND m.event = 'contact-information-fulfilled'
        AND m.updated <= chc.created
        ORDER BY m.id DESC
        LIMIT 1
    ) AS cm ON TRUE
    LEFT JOIN LATERAL (
        SELECT value AS is_csa_title_visible
        FROM configuration
        WHERE
            key = 'is_csa_title_visible'
            AND NOT deleted
            AND (created <= chc.created OR created IS NULL)
        ORDER BY id DESC
        LIMIT 1
    ) AS config ON TRUE
    LEFT JOIN LATERAL (
        SELECT
            first_name,
            last_name
        FROM "user" AS u
        WHERE u.id_code = c.customer_support_id
        AND u.created <= chc.created
        ORDER BY u.created DESC
        LIMIT 1
    ) AS cu ON TRUE
    LEFT JOIN LATERAL (
        SELECT
            first_name, last_name, display_name, status
        FROM "user" AS u
        WHERE u.id_code = m.max_msg_author_id
        AND u.created <= chc.created
        ORDER BY u.created DESC
        LIMIT 1
    ) AS mu ON TRUE
    LEFT JOIN LATERAL (
        SELECT
            chat_base_id,
            MIN(author_timestamp) AS first_support_timestamp
        FROM message
        WHERE
            chat_base_id = chc.chat_id
            AND author_role = 'backoffice-user'
            AND created <= chc.created
        GROUP BY chat_base_id
    ) AS fsm ON TRUE
    LEFT JOIN LATERAL (
        SELECT
            chat_base_id,
            MAX(author_timestamp) AS last_timestamp
        FROM message
        WHERE
            chat_base_id = chc.chat_id
            AND created <= chc.created
        GROUP BY chat_base_id
    ) AS lm ON TRUE
    LEFT JOIN LATERAL (
        SELECT value AS bot_institution_id
        FROM configuration
        WHERE
            key = 'bot_institution_id'
            AND NOT deleted
            AND (created <= chc.created OR created IS NULL)
        ORDER BY id DESC
        LIMIT 1
    ) AS bot_config ON TRUE
    WHERE c.base_id IS NOT NULL
    AND NOT EXISTS (
        SELECT 1
        FROM chat_history_comments AS chc_inner
        WHERE chc_inner.chat_id = chc.chat_id
        AND chc_inner.created = chc.created
        AND chc_inner.id < chc.id
    )

    UNION ALL

    -- Chat records without matching history comments (for ended chats)
    SELECT
        c.updated AS record_date,
        chc_latest.id AS chat_history_id,
        c.base_id AS chat_id,
        chc_latest.comment,
        chc_latest.created AS comment_added_date,
        chc_latest.author_display_name AS comment_author,
        m.min_id,
        m.max_id,
        m.first_message_content,
        m.max_msg_updated AS last_message_timestamp,
        m.max_msg_event AS last_message_event,
        m.max_msg_event_with_content AS last_message_event_with_content,
        m.last_message_content,
        m.last_message_including_empty_content,
        m.customer_messages_count,
        cm.contact_message_content,
        c.customer_support_id,
        m.max_msg_author_id AS author_id,
        c.customer_support_display_name,
        cu.first_name AS customer_support_first_name,
        cu.last_name AS customer_support_last_name,
        c.csa_title,
        c.end_user_id,
        c.end_user_first_name,
        c.end_user_last_name,
        c.end_user_email,
        c.end_user_phone,
        c.end_user_os,
        c.end_user_url,
        c.status,
        c.updated AS chat_updated,
        c.ended,
        c.forwarded_to,
        c.forwarded_to_name,
        c.received_from,
        c.received_from_name,
        c.external_id,
        c.labels,
        m.first_message_timestamp AS first_message_timestamp,
        c.created AS chat_created,
        c.feedback_text,
        c.feedback_rating,
        config.is_csa_title_visible,
        c.created,
        mu.display_name AS user_display_name,
        mu.status AS user_status,
        COALESCE(m.author_first_name, mu.first_name, mu.display_name) AS author_first_name,
        COALESCE(m.author_last_name, mu.last_name) AS author_last_name,
        fsm.first_support_timestamp,
        CASE
            WHEN fsm.first_support_timestamp IS NOT NULL AND lm.last_timestamp IS NOT NULL
            THEN ABS(EXTRACT(EPOCH FROM (fsm.first_support_timestamp - lm.last_timestamp)))
            ELSE NULL
        END AS duration_seconds,
        CASE
            WHEN c.customer_support_id = bot_config.bot_institution_id THEN TRUE
            ELSE FALSE
        END AS is_bot,
        bot_config.bot_institution_id
    FROM
        chat AS c
    LEFT JOIN LATERAL (
        SELECT *
        FROM chat_history_comments AS chc
        WHERE chc.chat_id = c.base_id
        AND chc.created <= c.updated
        ORDER BY chc.created DESC
        LIMIT 1
    ) AS chc_latest ON true
    LEFT JOIN LATERAL (
        WITH content_message_bounds AS (
            SELECT
                MAX(id) AS max_content_id,
                MIN(id) AS min_content_id
            FROM message AS m
            WHERE
                m.chat_base_id = c.base_id
                AND m.updated <= c.updated
                AND content <> ''
                AND content <> 'message-read'
        ),
        all_message_bounds AS (
            SELECT
                MAX(id) AS max_id
            FROM message AS m
            WHERE
                m.chat_base_id = c.base_id
                AND m.updated <= c.updated
        ),
        customer_messages_count AS (
            SELECT COUNT(inner_m.id) AS customer_messages_count
            FROM message AS inner_m
            WHERE
                inner_m.chat_base_id = c.base_id
                AND inner_m.author_role = 'end-user'
                AND (inner_m.event = '' OR inner_m.event IS NULL)
                AND inner_m.updated <= c.updated
        )
        SELECT
            cmb.min_content_id AS min_id,
            cmb.max_content_id AS max_id,
            min_msg.content AS first_message_content,
            min_msg.created AS first_message_timestamp,
            max_content_msg.content AS last_message_content,
            max_msg.content AS last_message_including_empty_content,
            max_msg.updated AS max_msg_updated,
            max_msg.event AS max_msg_event,
            max_content_msg.event AS max_msg_event_with_content,
            max_msg.author_id AS max_msg_author_id,
            max_msg.author_first_name AS author_first_name,
            max_msg.author_last_name AS author_last_name,
            cmc.customer_messages_count
        FROM content_message_bounds AS cmb
        CROSS JOIN all_message_bounds AS amb
        CROSS JOIN customer_messages_count AS cmc
        LEFT JOIN message AS min_msg ON min_msg.id = cmb.min_content_id
        LEFT JOIN message AS max_content_msg ON max_content_msg.id = cmb.max_content_id
        LEFT JOIN message AS max_msg ON max_msg.id = amb.max_id
    ) AS m ON TRUE
    LEFT JOIN LATERAL (
        SELECT
            m.content AS contact_message_content
        FROM message AS m
        WHERE m.chat_base_id = c.base_id
        AND m.event = 'contact-information-fulfilled'
        AND m.updated <= c.updated
        ORDER BY m.id DESC
        LIMIT 1
    ) AS cm ON TRUE
    LEFT JOIN LATERAL (
        SELECT value AS is_csa_title_visible
        FROM configuration
        WHERE
            key = 'is_csa_title_visible'
            AND NOT deleted
            AND (created <= c.updated OR created IS NULL)
        ORDER BY id DESC
        LIMIT 1
    ) AS config ON TRUE
    LEFT JOIN LATERAL (
        SELECT
            first_name,
            last_name
        FROM "user" AS u
        WHERE u.id_code = c.customer_support_id
        AND u.created <= c.updated
        ORDER BY u.created DESC
        LIMIT 1
    ) AS cu ON TRUE
    LEFT JOIN LATERAL (
        SELECT
            first_name, last_name, display_name, status
        FROM "user" AS u
        WHERE u.id_code = m.max_msg_author_id
        AND u.created <= c.updated
        ORDER BY u.created DESC
        LIMIT 1
    ) AS mu ON TRUE
    LEFT JOIN LATERAL (
        SELECT
            chat_base_id,
            MIN(author_timestamp) AS first_support_timestamp
        FROM message
        WHERE
            chat_base_id = c.base_id
            AND author_role = 'backoffice-user'
            AND created <= c.updated
        GROUP BY chat_base_id
    ) AS fsm ON TRUE
    LEFT JOIN LATERAL (
        SELECT
            chat_base_id,
            MAX(author_timestamp) AS last_timestamp
        FROM message
        WHERE
            chat_base_id = c.base_id
            AND created <= c.updated
        GROUP BY chat_base_id
    ) AS lm ON TRUE
    LEFT JOIN LATERAL (
        SELECT value AS bot_institution_id
        FROM configuration
        WHERE
            key = 'bot_institution_id'
            AND NOT deleted
            AND (created <= c.updated OR created IS NULL)
        ORDER BY id DESC
        LIMIT 1
    ) AS bot_config ON TRUE
    WHERE NOT EXISTS (
        SELECT 1
        FROM chat_history_comments AS chc
        WHERE chc.chat_id = c.base_id
        AND chc.created = c.updated
    )

    UNION ALL

    -- Message records without matching chats or history comments
    SELECT
        m.updated AS record_date,
        chc_latest.id AS chat_history_id,
        m.chat_base_id AS chat_id,
        chc_latest.comment,
        chc_latest.created AS comment_added_date,
        chc_latest.author_display_name AS comment_author,
        m_bounds.min_id,
        m_bounds.max_id,
        m_msg.content AS first_message_content,
        m.updated AS last_message_timestamp,
        m.event AS last_message_event,
        CASE
            WHEN m.content <> '' AND m.content <> 'message-read' THEN m.event
            ELSE NULL
        END AS last_message_event_with_content,
        CASE
            WHEN m.content <> '' AND m.content <> 'message-read' THEN m.content
            ELSE (SELECT content
                FROM message
                WHERE chat_base_id = m.chat_base_id
                AND content <> ''
                AND content <> 'message-read'
                AND updated <= m.updated
                ORDER BY id DESC
                LIMIT 1)
        END AS last_message_content,
        m.content AS last_message_including_empty_content,
        cmc.customer_messages_count,
        cm.contact_message_content,
        c.customer_support_id,
        m.author_id,
        c.customer_support_display_name,
        cu.first_name AS customer_support_first_name,
        cu.last_name AS customer_support_last_name,
        c.csa_title,
        c.end_user_id,
        c.end_user_first_name,
        c.end_user_last_name,
        c.end_user_email,
        c.end_user_phone,
        c.end_user_os,
        c.end_user_url,
        c.status,
        c.updated AS chat_updated,
        c.ended,
        c.forwarded_to,
        c.forwarded_to_name,
        c.received_from,
        c.received_from_name,
        c.external_id,
        c.labels,
        m_msg.created AS first_message_timestamp,
        c.created AS chat_created,
        c.feedback_text,
        c.feedback_rating,
        config.is_csa_title_visible,
        m.created,
        mu.display_name AS user_display_name,
        mu.status AS user_status,
        COALESCE(m.author_first_name, mu.first_name, mu.display_name) AS author_first_name,
        COALESCE(m.author_last_name, mu.last_name) AS author_last_name,
        fsm.first_support_timestamp,
        CASE
            WHEN fsm.first_support_timestamp IS NOT NULL AND lm.last_timestamp IS NOT NULL
            THEN ABS(EXTRACT(EPOCH FROM (fsm.first_support_timestamp - lm.last_timestamp)))
            ELSE NULL
        END AS duration_seconds,
        CASE
            WHEN c.customer_support_id = bot_config.bot_institution_id THEN TRUE
            ELSE FALSE
        END AS is_bot,
        bot_config.bot_institution_id
    FROM
        message AS m
    LEFT JOIN LATERAL (
        SELECT *
        FROM chat_history_comments AS chc
        WHERE chc.chat_id = m.chat_base_id
        AND chc.created <= m.updated
        ORDER BY chc.created DESC
        LIMIT 1
    ) AS chc_latest ON true
    LEFT JOIN LATERAL (
        SELECT *
        FROM chat AS c
        WHERE c.base_id = m.chat_base_id
        AND c.updated <= m.updated
        ORDER BY c.updated DESC
        LIMIT 1
    ) AS c ON true
    LEFT JOIN LATERAL (
        WITH message_bounds AS (
            SELECT
                MIN(id) AS min_id
            FROM message AS inner_m
            WHERE
                inner_m.chat_base_id = m.chat_base_id
                AND inner_m.updated <= m.updated
                AND inner_m.content <> ''
                AND inner_m.content <> 'message-read'
        )
        SELECT
            mb.min_id,
            m.id AS max_id
        FROM message_bounds AS mb
    ) AS m_bounds ON TRUE
    LEFT JOIN message AS m_msg ON m_msg.id = m_bounds.min_id
    LEFT JOIN LATERAL (
        SELECT COUNT(inner_m.id) AS customer_messages_count
        FROM message AS inner_m
        WHERE
            inner_m.chat_base_id = m.chat_base_id
            AND inner_m.author_role = 'end-user'
            AND (inner_m.event = '' OR inner_m.event IS NULL)
            AND inner_m.updated <= m.updated
    ) AS cmc ON TRUE
    LEFT JOIN LATERAL (
        SELECT
            m_cm.content AS contact_message_content
        FROM message AS m_cm
        WHERE m_cm.chat_base_id = m.chat_base_id
        AND m_cm.event = 'contact-information-fulfilled'
        AND m_cm.updated <= m.updated
        ORDER BY m_cm.id DESC
        LIMIT 1
    ) AS cm ON TRUE
    LEFT JOIN LATERAL (
        SELECT value AS is_csa_title_visible
        FROM configuration
        WHERE
            key = 'is_csa_title_visible'
            AND NOT deleted
            AND (created <= m.updated OR created IS NULL)
        ORDER BY id DESC
        LIMIT 1
    ) AS config ON TRUE
    LEFT JOIN LATERAL (
        SELECT
            first_name,
            last_name
        FROM "user" AS u
        WHERE u.id_code = c.customer_support_id
        AND u.created <= m.updated
        ORDER BY u.created DESC
        LIMIT 1
    ) AS cu ON TRUE
    LEFT JOIN LATERAL (
        SELECT
            first_name, last_name, display_name, status
        FROM "user" AS u
        WHERE u.id_code = m.author_id
        AND u.created <= m.updated
        ORDER BY u.created DESC
        LIMIT 1
    ) AS mu ON TRUE
    LEFT JOIN LATERAL (
        SELECT
            chat_base_id,
            MIN(author_timestamp) AS first_support_timestamp
        FROM message
        WHERE
            chat_base_id = m.chat_base_id
            AND author_role = 'backoffice-user'
            AND updated <= m.updated
        GROUP BY chat_base_id
    ) AS fsm ON TRUE
    LEFT JOIN LATERAL (
        SELECT
            chat_base_id,
            MAX(author_timestamp) AS last_timestamp
        FROM message
        WHERE
            chat_base_id = m.chat_base_id
            AND updated <= m.updated
        GROUP BY chat_base_id
    ) AS lm ON TRUE
    LEFT JOIN LATERAL (
        SELECT value AS bot_institution_id
        FROM configuration
        WHERE
            key = 'bot_institution_id'
            AND NOT deleted
            AND (created <= m.updated OR created IS NULL)
        ORDER BY id DESC
        LIMIT 1
    ) AS bot_config ON TRUE
    WHERE c.base_id IS NOT NULL
    AND NOT EXISTS (
        SELECT 1
        FROM chat_history_comments AS chc
        WHERE chc.chat_id = m.chat_base_id
        AND chc.created = m.updated
    )
    AND NOT EXISTS (
        SELECT 1
        FROM chat AS cx
        WHERE cx.base_id = m.chat_base_id
        AND cx.updated = m.updated
    )

    UNION ALL

    -- User records that might have changed but no corresponding chat/message/history changes
    SELECT
        u.created AS record_date,
        chc_latest.id AS chat_history_id,
        c.base_id AS chat_id,
        chc_latest.comment,
        chc_latest.created AS comment_added_date,
        chc_latest.author_display_name AS comment_author,
        m.min_id,
        m.max_id,
        m.first_message_content,
        m.max_msg_updated AS last_message_timestamp,
        m.max_msg_event AS last_message_event,
        m.max_msg_event_with_content AS last_message_event_with_content,
        m.last_message_content,
        m.last_message_including_empty_content,
        m.customer_messages_count,
        cm.contact_message_content,
        c.customer_support_id,
        m.max_msg_author_id AS author_id,
        c.customer_support_display_name,
        u.first_name AS customer_support_first_name,
        u.last_name AS customer_support_last_name,
        c.csa_title,
        c.end_user_id,
        c.end_user_first_name,
        c.end_user_last_name,
        c.end_user_email,
        c.end_user_phone,
        c.end_user_os,
        c.end_user_url,
        c.status,
        c.updated AS chat_updated,
        c.ended,
        c.forwarded_to,
        c.forwarded_to_name,
        c.received_from,
        c.received_from_name,
        c.external_id,
        c.labels,
        m.first_message_timestamp AS first_message_timestamp,
        c.created AS chat_created,
        c.feedback_text,
        c.feedback_rating,
        config.is_csa_title_visible,
        u.created,
        CASE
            WHEN u.id_code = m.max_msg_author_id THEN u.display_name
            ELSE mu.display_name
        END AS user_display_name,
        CASE
            WHEN u.id_code = m.max_msg_author_id THEN u.status
            ELSE mu.status
        END AS user_status,
        COALESCE(
            m.author_first_name,
            CASE
                WHEN u.id_code = m.max_msg_author_id THEN u.first_name
                ELSE mu.first_name
            END,
            u.display_name
        ) AS author_first_name,
        COALESCE(
            m.author_last_name,
            CASE
                WHEN u.id_code = m.max_msg_author_id THEN u.last_name
                ELSE mu.last_name
            END
        ) AS author_last_name,
        fsm.first_support_timestamp,
        CASE
            WHEN fsm.first_support_timestamp IS NOT NULL AND lm.last_timestamp IS NOT NULL
            THEN ABS(EXTRACT(EPOCH FROM (fsm.first_support_timestamp - lm.last_timestamp)))
            ELSE NULL
        END AS duration_seconds,
        CASE
            WHEN c.customer_support_id = bot_config.bot_institution_id THEN TRUE
            ELSE FALSE
        END AS is_bot,
        bot_config.bot_institution_id
    FROM
        "user" AS u
    LEFT JOIN LATERAL (
        SELECT *
        FROM chat AS c
        WHERE c.customer_support_id = u.id_code
        AND c.updated <= u.created
        ORDER BY c.updated DESC
        LIMIT 1
    ) AS c ON true
    LEFT JOIN LATERAL (
        SELECT *
        FROM chat_history_comments AS chc
        WHERE chc.chat_id = c.base_id
        AND chc.created <= u.created
        ORDER BY chc.created DESC
        LIMIT 1
    ) AS chc_latest ON true
    LEFT JOIN LATERAL (
        WITH content_message_bounds AS (
            SELECT
                MAX(id) AS max_content_id,
                MIN(id) AS min_content_id
            FROM message AS m
            WHERE
                m.chat_base_id = c.base_id
                AND m.updated <= u.created
                AND content <> ''
                AND content <> 'message-read'
        ),
        all_message_bounds AS (
            SELECT
                MAX(id) AS max_id
            FROM message AS m
            WHERE
                m.chat_base_id = c.base_id
                AND m.updated <= u.created
        ),
        customer_messages_count AS (
            SELECT COUNT(inner_m.id) AS customer_messages_count
            FROM message AS inner_m
            WHERE
                inner_m.chat_base_id = c.base_id
                AND inner_m.author_role = 'end-user'
                AND (inner_m.event = '' OR inner_m.event IS NULL)
                AND inner_m.updated <= u.created
        )
        SELECT
            cmb.min_content_id AS min_id,
            cmb.max_content_id AS max_id,
            min_msg.content AS first_message_content,
            min_msg.created AS first_message_timestamp,
            max_content_msg.content AS last_message_content,
            max_msg.content AS last_message_including_empty_content,
            max_msg.updated AS max_msg_updated,
            max_msg.event AS max_msg_event,
            max_content_msg.event AS max_msg_event_with_content,
            max_msg.author_id AS max_msg_author_id,
            max_msg.author_first_name AS author_first_name,
            max_msg.author_last_name AS author_last_name,
            cmc.customer_messages_count
        FROM content_message_bounds AS cmb
        CROSS JOIN all_message_bounds AS amb
        CROSS JOIN customer_messages_count AS cmc
        LEFT JOIN message AS min_msg ON min_msg.id = cmb.min_content_id
        LEFT JOIN message AS max_content_msg ON max_content_msg.id = cmb.max_content_id
        LEFT JOIN message AS max_msg ON max_msg.id = amb.max_id
    ) AS m ON TRUE
    LEFT JOIN LATERAL (
        SELECT
            m.content AS contact_message_content
        FROM message AS m
        WHERE m.chat_base_id = c.base_id
        AND m.event = 'contact-information-fulfilled'
        AND m.updated <= u.created
        ORDER BY m.id DESC
        LIMIT 1
    ) AS cm ON TRUE
    LEFT JOIN LATERAL (
        SELECT value AS is_csa_title_visible
        FROM configuration
        WHERE
            key = 'is_csa_title_visible'
            AND NOT deleted
            AND (created <= u.created OR created IS NULL)
        ORDER BY id DESC
        LIMIT 1
    ) AS config ON TRUE
    LEFT JOIN LATERAL (
        SELECT
            first_name, last_name, display_name, status
        FROM "user" AS mu
        WHERE mu.id_code = m.max_msg_author_id
        AND mu.created <= u.created
        AND mu.id_code <> u.id_code
        ORDER BY mu.created DESC
        LIMIT 1
    ) AS mu ON TRUE
    LEFT JOIN LATERAL (
        SELECT
            chat_base_id,
            MIN(author_timestamp) AS first_support_timestamp
        FROM message
        WHERE
            chat_base_id = c.base_id
            AND author_role = 'backoffice-user'
            AND created <= u.created
        GROUP BY chat_base_id
    ) AS fsm ON TRUE
    LEFT JOIN LATERAL (
        SELECT
            chat_base_id,
            MAX(author_timestamp) AS last_timestamp
        FROM message
        WHERE
            chat_base_id = c.base_id
            AND created <= u.created
        GROUP BY chat_base_id
    ) AS lm ON TRUE
    LEFT JOIN LATERAL (
        SELECT value AS bot_institution_id
        FROM configuration
        WHERE
            key = 'bot_institution_id'
            AND NOT deleted
            AND (created <= u.created OR created IS NULL)
        ORDER BY id DESC
        LIMIT 1
    ) AS bot_config ON TRUE
    WHERE c.base_id IS NOT NULL
    AND NOT EXISTS (
        SELECT 1
        FROM chat_history_comments AS chc
        WHERE chc.chat_id = c.base_id
        AND chc.created = u.created
    )
    AND NOT EXISTS (
        SELECT 1
        FROM chat AS cx
        WHERE cx.base_id = c.base_id
        AND cx.updated = u.created
    )
    AND NOT EXISTS (
        SELECT 1
        FROM message AS mx
        WHERE mx.chat_base_id = c.base_id
        AND mx.created = u.created
    )
),
-- Configuration changes processing
config_changes AS (
    SELECT
        config.id,
        config.created,
        config.key,
        config.value
    FROM configuration AS config
    WHERE NOT config.deleted
    AND (config.key = 'is_csa_title_visible' OR config.key = 'bot_institution_id')
),
active_chats_at_config_changes AS (
    SELECT
        cc.created AS config_timestamp,
        cc.key AS config_key,
        cc.value AS config_value,
        c.base_id AS chat_id
    FROM config_changes AS cc
    CROSS JOIN (
        SELECT DISTINCT c.base_id, c.created, c.ended
        FROM chat AS c
    ) AS c
    WHERE
        c.created <= cc.created
        AND (c.ended IS NULL OR c.ended > cc.created)
),
config_records AS (
    SELECT
        acc.config_timestamp AS record_date,
        chc_latest.id AS chat_history_id,
        acc.chat_id,
        chc_latest.comment,
        chc_latest.created AS comment_added_date,
        chc_latest.author_display_name AS comment_author,
        m.min_id,
        m.max_id,
        m.first_message_content,
        m.max_msg_updated AS last_message_timestamp,
        m.max_msg_event AS last_message_event,
        m.max_msg_event_with_content AS last_message_event_with_content,
        m.last_message_content,
        m.last_message_including_empty_content,
        m.customer_messages_count,
        cm.contact_message_content,
        c.customer_support_id,
        m.max_msg_author_id AS author_id,
        c.customer_support_display_name,
        cu.first_name AS customer_support_first_name,
        cu.last_name AS customer_support_last_name,
        c.csa_title,
        c.end_user_id,
        c.end_user_first_name,
        c.end_user_last_name,
        c.end_user_email,
        c.end_user_phone,
        c.end_user_os,
        c.end_user_url,
        c.status,
        c.updated AS chat_updated,
        c.ended,
        c.forwarded_to,
        c.forwarded_to_name,
        c.received_from,
        c.received_from_name,
        c.external_id,
        c.labels,
        m.first_message_timestamp AS first_message_timestamp,
        c.created AS chat_created,
        c.feedback_text,
        c.feedback_rating,
        CASE
            WHEN acc.config_key = 'is_csa_title_visible' THEN acc.config_value
            ELSE csa_config.value
        END AS is_csa_title_visible,
        acc.config_timestamp AS created,
        mu.display_name AS user_display_name,
        mu.status AS user_status,
        COALESCE(m.author_first_name, mu.first_name, mu.display_name) AS author_first_name,
        COALESCE(m.author_last_name, mu.last_name) AS author_last_name,
        fsm.first_support_timestamp,
        CASE
            WHEN fsm.first_support_timestamp IS NOT NULL AND lm.last_timestamp IS NOT NULL
            THEN ABS(EXTRACT(EPOCH FROM (fsm.first_support_timestamp - lm.last_timestamp)))
            ELSE NULL
        END AS duration_seconds,
        CASE
            WHEN c.customer_support_id = CASE
                                            WHEN acc.config_key = 'bot_institution_id' THEN acc.config_value
                                            ELSE bot_config.value
                                         END THEN TRUE
            ELSE FALSE
        END AS is_bot,
        CASE
            WHEN acc.config_key = 'bot_institution_id' THEN acc.config_value
            ELSE bot_config.value
        END AS bot_institution_id
    FROM active_chats_at_config_changes AS acc
    LEFT JOIN LATERAL (
        SELECT *
        FROM chat AS c
        WHERE c.base_id = acc.chat_id
        AND c.updated <= acc.config_timestamp
        ORDER BY c.updated DESC
        LIMIT 1
    ) AS c ON true
    LEFT JOIN LATERAL (
        SELECT *
        FROM chat_history_comments AS chc
        WHERE chc.chat_id = acc.chat_id
        AND chc.created <= acc.config_timestamp
        ORDER BY chc.created DESC
        LIMIT 1
    ) AS chc_latest ON true
    LEFT JOIN LATERAL (
        WITH content_message_bounds AS (
            SELECT
                MAX(id) AS max_content_id,
                MIN(id) AS min_content_id
            FROM message AS m
            WHERE
                m.chat_base_id = acc.chat_id
                AND m.updated <= acc.config_timestamp
                AND content <> ''
                AND content <> 'message-read'
        ),
        all_message_bounds AS (
            SELECT
                MAX(id) AS max_id
            FROM message AS m
            WHERE
                m.chat_base_id = acc.chat_id
                AND m.updated <= acc.config_timestamp
        ),
        customer_messages_count AS (
            SELECT COUNT(inner_m.id) AS customer_messages_count
            FROM message AS inner_m
            WHERE
                inner_m.chat_base_id = acc.chat_id
                AND inner_m.author_role = 'end-user'
                AND (inner_m.event = '' OR inner_m.event IS NULL)
                AND inner_m.updated <= acc.config_timestamp
        )
        SELECT
            cmb.min_content_id AS min_id,
            cmb.max_content_id AS max_id,
            min_msg.content AS first_message_content,
            min_msg.created AS first_message_timestamp,
            max_content_msg.content AS last_message_content,
            max_msg.content AS last_message_including_empty_content,
            max_msg.updated AS max_msg_updated,
            max_msg.event AS max_msg_event,
            max_content_msg.event AS max_msg_event_with_content,
            max_msg.author_id AS max_msg_author_id,
            max_msg.author_first_name AS author_first_name,
            max_msg.author_last_name AS author_last_name,
            cmc.customer_messages_count
        FROM content_message_bounds AS cmb
        CROSS JOIN all_message_bounds AS amb
        CROSS JOIN customer_messages_count AS cmc
        LEFT JOIN message AS min_msg ON min_msg.id = cmb.min_content_id
        LEFT JOIN message AS max_content_msg ON max_content_msg.id = cmb.max_content_id
        LEFT JOIN message AS max_msg ON max_msg.id = amb.max_id
    ) AS m ON TRUE
    LEFT JOIN LATERAL (
        SELECT
            m.content AS contact_message_content
        FROM message AS m
        WHERE m.chat_base_id = acc.chat_id
        AND m.event = 'contact-information-fulfilled'
        AND m.updated <= acc.config_timestamp
        ORDER BY m.id DESC
        LIMIT 1
    ) AS cm ON TRUE
    LEFT JOIN LATERAL (
        SELECT
            first_name,
            last_name
        FROM "user" AS u
        WHERE u.id_code = c.customer_support_id
        AND u.created <= acc.config_timestamp
        ORDER BY u.created DESC
        LIMIT 1
    ) AS cu ON TRUE
    LEFT JOIN LATERAL (
        SELECT
            first_name, last_name, display_name, status
        FROM "user" AS u
        WHERE u.id_code = m.max_msg_author_id
        AND u.created <= acc.config_timestamp
        ORDER BY u.created DESC
        LIMIT 1
    ) AS mu ON TRUE
    LEFT JOIN LATERAL (
        SELECT
            chat_base_id,
            MIN(author_timestamp) AS first_support_timestamp
        FROM message
        WHERE
            chat_base_id = acc.chat_id
            AND author_role = 'backoffice-user'
            AND created <= acc.config_timestamp
        GROUP BY chat_base_id
    ) AS fsm ON TRUE
    LEFT JOIN LATERAL (
        SELECT
            chat_base_id,
            MAX(author_timestamp) AS last_timestamp
        FROM message
        WHERE
            chat_base_id = acc.chat_id
            AND created <= acc.config_timestamp
        GROUP BY chat_base_id
    ) AS lm ON TRUE
    LEFT JOIN LATERAL (
        SELECT value
        FROM configuration
        WHERE
            key = 'bot_institution_id'
            AND NOT deleted
            AND (created <= acc.config_timestamp OR created IS NULL)
            AND key <> acc.config_key
        ORDER BY id DESC
        LIMIT 1
    ) AS bot_config ON acc.config_key <> 'bot_institution_id'
    LEFT JOIN LATERAL (
        SELECT value
        FROM configuration
        WHERE
            key = 'is_csa_title_visible'
            AND NOT deleted
            AND (created <= acc.config_timestamp OR created IS NULL)
            AND key <> acc.config_key
        ORDER BY id DESC
        LIMIT 1
    ) AS csa_config ON acc.config_key <> 'is_csa_title_visible'
    WHERE NOT EXISTS (
        SELECT 1
        FROM chat_history_comments AS chc
        WHERE chc.chat_id = acc.chat_id
        AND chc.created = acc.config_timestamp
    )
    AND NOT EXISTS (
        SELECT 1
        FROM chat AS cx
        WHERE cx.base_id = acc.chat_id
        AND cx.updated = acc.config_timestamp
    )
    AND NOT EXISTS (
        SELECT 1
        FROM message AS mx
        WHERE mx.chat_base_id = acc.chat_id
        AND mx.created = acc.config_timestamp
    )
    AND NOT EXISTS (
        SELECT 1
        FROM "user" AS ux
        WHERE ux.id_code = c.customer_support_id
        AND ux.created = acc.config_timestamp
    )
),
-- NPS calculation done once at the end
rated_chats AS (
    SELECT MAX(feedback_rating) AS rating
    FROM chat
    WHERE feedback_rating IS NOT NULL
    GROUP BY base_id
),
rated_chats_count AS (
    SELECT COUNT(rating) AS total FROM rated_chats
),
promoters AS (
    SELECT COUNT(rating) AS p FROM rated_chats
    WHERE rating >= 9
),
detractors AS (
    SELECT COUNT(rating) AS d FROM rated_chats
    WHERE rating <= 6
),
nps_calc AS (
    SELECT ROUND(
        ((p / (GREATEST(total, 1) * 1.0)) - (d / (GREATEST(total, 1) * 1.0))) * 100.0,
        2
    ) AS nps_value
    FROM rated_chats_count
    CROSS JOIN promoters
    CROSS JOIN detractors
)
-- Combine the original record and the configuration records
SELECT
    chat_id,
    customer_support_id,
    customer_support_display_name,
    customer_support_first_name,
    customer_support_last_name,
    end_user_id,
    end_user_first_name,
    end_user_last_name,
    end_user_email,
    end_user_phone,
    end_user_os,
    end_user_url,
    status,
    first_message_timestamp,
    chat_created AS created,
    chat_updated AS updated,
    record_date AS denormalized_record_created,
    ended,
    forwarded_to,
    forwarded_to_name,
    received_from,
    received_from_name,
    external_id,
    labels,
    comment,
    comment_added_date,
    comment_author,
    user_display_name,
    user_status,
    author_first_name,
    author_last_name,
    first_message_content AS first_message,
    last_message_content AS last_message,
    last_message_including_empty_content,
    contact_message_content AS contacts_message,
    last_message_timestamp,
    feedback_text,
    feedback_rating,
    (SELECT nps_value FROM nps_calc) AS nps,
    CASE
        WHEN is_csa_title_visible = 'true' THEN csa_title
        ELSE ''
    END AS csa_title,
    CASE
        WHEN last_message_event IS NULL THEN NULL
        ELSE LOWER(last_message_event)
    END AS last_message_event,
    CASE
        WHEN last_message_event_with_content IS NULL THEN NULL
        ELSE LOWER(last_message_event_with_content)
    END AS last_message_event_with_content,
    duration_seconds AS chat_duration_in_seconds,
    is_bot,
    customer_messages_count
FROM (
    SELECT * FROM combined_records
    UNION ALL
    SELECT * FROM config_records
) AS all_records
CROSS JOIN nps_calc
WHERE chat_id IN (SELECT base_id FROM chat)
ORDER BY denormalized_record_created;