-- liquibase formatted sql
-- changeset Artsiom Beida:20250424093709 ignore:true

CREATE TABLE denormalized_user_data (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    login CHARACTER VARYING(50) NOT NULL,
    first_name CHARACTER VARYING(50),
    last_name CHARACTER VARYING(50),
    id_code CHARACTER VARYING(50) NOT NULL,
    display_name CHARACTER VARYING(50),
    password_hash TEXT,
    csa_title CHARACTER VARYING,
    csa_email CHARACTER VARYING,
    department TEXT,
    authority_name CHARACTER VARYING [],
    user_status USER_STATUS,
    status STATUS,
    active BOOLEAN DEFAULT false,
    status_comment TEXT DEFAULT '',
    csa_created TIMESTAMP WITH TIME ZONE,
    forwarded_chat_popup_notifications BOOLEAN DEFAULT false,
    forwarded_chat_sound_notifications BOOLEAN DEFAULT true,
    forwarded_chat_email_notifications BOOLEAN DEFAULT false,
    new_chat_popup_notifications BOOLEAN DEFAULT false,
    new_chat_sound_notifications BOOLEAN DEFAULT false,
    use_autocorrect BOOLEAN DEFAULT false,
    new_chat_email_notifications BOOLEAN DEFAULT false,
    created TIMESTAMP WITH TIME ZONE DEFAULT now()
);

ALTER TABLE denormalized_user_data ADD PRIMARY KEY (id);

-- For simpler queries that filter by id_code and order by created
CREATE INDEX idx_denormalized_user_data_id_code_created ON denormalized_user_data (id_code, created DESC);

-- For queries that filter by status
CREATE INDEX idx_denormalized_user_data_status ON denormalized_user_data (status);

-- For queries that filter by user_status
CREATE INDEX idx_denormalized_user_data_user_status ON denormalized_user_data (user_status);

-- For queries that filter by csa_created date ranges and require user identification
CREATE INDEX idx_denormalized_user_data_csa_created_id_code ON denormalized_user_data (csa_created, id_code);

-- For the complex search/sort query
CREATE INDEX idx_complex_search_sort ON denormalized_user_data (
    user_status,
    id_code,
    created DESC,
    first_name,
    last_name,
    display_name,
    csa_title,
    csa_email,
    department,
    status
);

-- For array operations
CREATE INDEX idx_denormalized_user_data_authority_name ON denormalized_user_data USING gin (authority_name);


-- Now insert the data ordering by created timestamp to ensure IDs align with timestamps
-- Insert data into the denormalized table
INSERT INTO denormalized_user_data (
    login,
    first_name,
    last_name,
    id_code,
    display_name,
    password_hash,
    csa_title,
    csa_email,
    department,
    authority_name,
    user_status,
    status,
    active,
    status_comment,
    csa_created,
    forwarded_chat_popup_notifications,
    forwarded_chat_sound_notifications,
    forwarded_chat_email_notifications,
    new_chat_popup_notifications,
    new_chat_sound_notifications,
    use_autocorrect,
    new_chat_email_notifications,
    created
)
-- Combine all data sources and order by created timestamp
WITH combined_records AS (
    -- Activity records
    SELECT
        COALESCE(u.login, 'unknown_' || csa.id_code) AS login,
        u.first_name,
        u.last_name,
        csa.id_code,
        u.display_name,
        u.password_hash,
        u.csa_title,
        u.csa_email,
        u.department,
        COALESCE(ua.authority_name, '{}') AS authority_name,
        u.status AS user_status,
        csa.status,
        COALESCE(csa.active, false) AS active,
        csa.status_comment,
        csa.created AS csa_created,
        COALESCE(ups.forwarded_chat_popup_notifications, false) AS forwarded_chat_popup_notifications,
        COALESCE(ups.forwarded_chat_sound_notifications, true) AS forwarded_chat_sound_notifications,
        COALESCE(ups.forwarded_chat_email_notifications, false) AS forwarded_chat_email_notifications,
        COALESCE(ups.new_chat_popup_notifications, false) AS new_chat_popup_notifications,
        COALESCE(ups.new_chat_sound_notifications, false) AS new_chat_sound_notifications,
        COALESCE(ups.use_autocorrect, false) AS use_autocorrect,
        COALESCE(ups.new_chat_email_notifications, false) AS new_chat_email_notifications,
        csa.created
    FROM
        customer_support_agent_activity AS csa
    LEFT JOIN LATERAL (
        SELECT *
        FROM "user" AS u
        WHERE u.id_code = csa.id_code
        AND u.created <= csa.created
        ORDER BY u.created DESC
        LIMIT 1
    ) AS u ON true
    LEFT JOIN LATERAL (
        SELECT *
        FROM user_authority AS ua
        WHERE ua.user_id = csa.id_code
        AND ua.created <= csa.created
        ORDER BY ua.created DESC
        LIMIT 1
    ) AS ua ON true
    LEFT JOIN user_profile_settings AS ups ON ups.user_id = csa.id_code

    UNION ALL

    -- User records without matching activity timestamps
    SELECT
        u.login,
        u.first_name,
        u.last_name,
        u.id_code,
        u.display_name,
        u.password_hash,
        u.csa_title,
        u.csa_email,
        u.department,
        COALESCE(ua.authority_name, '{}') AS authority_name,
        u.status AS user_status,
        csa.status,  -- Use CSA status from LATERAL join
        COALESCE(csa.active, false) AS active,  -- Use CSA active from LATERAL join
        csa.status_comment,
        csa.created AS csa_created,
        COALESCE(ups.forwarded_chat_popup_notifications, false) AS forwarded_chat_popup_notifications,
        COALESCE(ups.forwarded_chat_sound_notifications, true) AS forwarded_chat_sound_notifications,
        COALESCE(ups.forwarded_chat_email_notifications, false) AS forwarded_chat_email_notifications,
        COALESCE(ups.new_chat_popup_notifications, false) AS new_chat_popup_notifications,
        COALESCE(ups.new_chat_sound_notifications, false) AS new_chat_sound_notifications,
        COALESCE(ups.use_autocorrect, false) AS use_autocorrect,
        COALESCE(ups.new_chat_email_notifications, false) AS new_chat_email_notifications,
        u.created
    FROM
        "user" AS u
    LEFT JOIN LATERAL (
        SELECT *
        FROM customer_support_agent_activity AS csa
        WHERE csa.id_code = u.id_code
        AND csa.created <= u.created
        ORDER BY csa.created DESC
        LIMIT 1
    ) AS csa ON true
    LEFT JOIN LATERAL (
        SELECT *
        FROM user_authority AS ua
        WHERE ua.user_id = u.id_code
        AND ua.created <= u.created
        ORDER BY ua.created DESC
        LIMIT 1
    ) AS ua ON true
    LEFT JOIN user_profile_settings AS ups ON ups.user_id = u.id_code
    WHERE NOT EXISTS (
        SELECT 1
        FROM customer_support_agent_activity AS csax
        WHERE csax.id_code = u.id_code
        AND csax.created = u.created
    )

    UNION ALL

    -- Authority records without matching activity or user timestamps
    SELECT
        COALESCE(u.login, 'unknown_' || ua.user_id) AS login,
        u.first_name,
        u.last_name,
        ua.user_id AS id_code,
        u.display_name,
        u.password_hash,
        u.csa_title,
        u.csa_email,
        u.department,
        ua.authority_name,
        u.status AS user_status,
        csa.status,  -- Use CSA status from LATERAL join
        COALESCE(csa.active, false) AS active,  -- Use CSA active from LATERAL join
        csa.status_comment,
        csa.created AS csa_created,
        COALESCE(ups.forwarded_chat_popup_notifications, false) AS forwarded_chat_popup_notifications,
        COALESCE(ups.forwarded_chat_sound_notifications, true) AS forwarded_chat_sound_notifications,
        COALESCE(ups.forwarded_chat_email_notifications, false) AS forwarded_chat_email_notifications,
        COALESCE(ups.new_chat_popup_notifications, false) AS new_chat_popup_notifications,
        COALESCE(ups.new_chat_sound_notifications, false) AS new_chat_sound_notifications,
        COALESCE(ups.use_autocorrect, false) AS use_autocorrect,
        COALESCE(ups.new_chat_email_notifications, false) AS new_chat_email_notifications,
        ua.created
    FROM
        user_authority AS ua
    LEFT JOIN LATERAL (
        SELECT *
        FROM "user" AS u
        WHERE u.id_code = ua.user_id
        AND u.created <= ua.created
        ORDER BY u.created DESC
        LIMIT 1
    ) AS u ON true
    LEFT JOIN LATERAL (
        SELECT *
        FROM customer_support_agent_activity AS csa
        WHERE csa.id_code = ua.user_id
        AND csa.created <= ua.created
        ORDER BY csa.created DESC
        LIMIT 1
    ) AS csa ON true
    LEFT JOIN user_profile_settings AS ups ON ups.user_id = ua.user_id
    WHERE NOT EXISTS (
        SELECT 1
        FROM customer_support_agent_activity AS csax
        WHERE csax.id_code = ua.user_id
        AND csax.created = ua.created
    )
    AND NOT EXISTS (
        SELECT 1
        FROM "user" AS ux
        WHERE ux.id_code = ua.user_id
        AND ux.created = ua.created
    )
)
SELECT * FROM combined_records
ORDER BY created;

DROP TABLE customer_support_agent_activity;
DROP TABLE user_authority;
DROP TABLE user_profile_settings;