-- liquibase formatted sql
-- changeset Artsiom Beida:20250502000000 ignore:true
CREATE TABLE denormalized_chat (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    chat_id character varying NOT NULL,
    customer_support_id character varying,
    customer_support_display_name character varying,
    customer_support_first_name character varying,
    customer_support_last_name character varying,
    end_user_id character varying,
    end_user_first_name character varying,
    end_user_last_name character varying,
    end_user_email character varying,
    end_user_phone character varying,
    end_user_os character varying,
    end_user_url character varying,
    status character varying,
    first_message_timestamp timestamp with time zone,
    last_message_author_id character varying,
    created timestamp with time zone,
    updated timestamp with time zone,
    denormalized_record_created timestamp with time zone NOT NULL DEFAULT now(),
    ended timestamp with time zone,
    forwarded_to character varying,
    forwarded_to_name character varying,
    received_from character varying,
    received_from_name character varying,
    external_id character varying,
    labels character varying [],
    comment text,
    comment_added_date timestamp with time zone,
    comment_author character varying,
    first_message text,
    last_message text,
    last_message_including_empty_content text,
    contacts_message text,
    last_message_timestamp timestamp with time zone,
    feedback_text text,
    feedback_rating integer,
    csa_title character varying,
    last_message_event character varying,
    last_message_event_with_content character varying,
    chat_duration_in_seconds numeric,
    first_support_timestamp timestamp with time zone,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    customer_messages_count integer,
    -- New columns
    last_message_with_content_and_not_rating_or_forward text,
    last_message_with_not_rating_or_forward_events_timestamp timestamp with time zone,
    last_non_empty_message_event character varying,
    all_messages text[],
    CONSTRAINT denormalized_chat_pkey PRIMARY KEY (id)
);

-- Index #1
CREATE INDEX idx_denormalized_chat_chatid_record_created 
ON denormalized_chat(chat_id, denormalized_record_created DESC);

-- Index #2
CREATE INDEX idx_denormalized_chat_status_ended_enduser 
ON denormalized_chat(status, ended, end_user_id);

-- Index #3
CREATE INDEX idx_denormalized_chat_ended_status_support_created 
ON denormalized_chat(ended, status, customer_support_id, created);

-- Index #4
CREATE INDEX idx_denormalized_chat_status 
ON denormalized_chat(status);

-- Index #5
CREATE INDEX idx_denormalized_chat_ended 
ON denormalized_chat(ended);

-- Index #6
CREATE INDEX idx_denormalized_chat_customer_support_id 
ON denormalized_chat(customer_support_id);

-- Index #7
CREATE INDEX idx_denormalized_chat_first_message 
ON denormalized_chat(first_message);

-- Index #8
CREATE INDEX idx_denormalized_chat_last_message 
ON denormalized_chat(last_message);

-- Index #9
CREATE INDEX idx_denormalized_chat_first_message_timestamp 
ON denormalized_chat(first_message_timestamp);

-- Index #10
CREATE INDEX idx_denormalized_chat_customer_support_display_name 
ON denormalized_chat(customer_support_display_name);

-- Index #11
CREATE INDEX idx_denormalized_chat_end_user_first_name 
ON denormalized_chat(end_user_first_name);

-- Index #12
CREATE INDEX idx_denormalized_chat_end_user_id 
ON denormalized_chat(end_user_id);

-- Index #13
CREATE INDEX idx_denormalized_chat_contacts_message 
ON denormalized_chat(contacts_message);

-- Index #14
CREATE INDEX idx_denormalized_chat_comment 
ON denormalized_chat(comment);

-- Index #15
CREATE INDEX idx_denormalized_chat_labels 
ON denormalized_chat(labels);

-- Index #16
CREATE INDEX idx_denormalized_chat_last_message_event 
ON denormalized_chat(last_message_event);

-- Index #17
CREATE INDEX idx_denormalized_chat_feedback_rating 
ON denormalized_chat(feedback_rating);

-- Index #18
CREATE INDEX idx_denormalized_chat_cs_first_last_name 
ON denormalized_chat(customer_support_first_name, customer_support_last_name);

-- Index #19
CREATE INDEX idx_denormalized_chat_created 
ON denormalized_chat(created);

-- Index #20
CREATE INDEX idx_denormalized_chat_all_messages 
ON denormalized_chat USING gin(all_messages);

-- Index #21
CREATE INDEX idx_denormalized_chat_duration 
ON denormalized_chat(chat_duration_in_seconds);

-- Index #22
CREATE INDEX idx_denormalized_chat_last_message_no_rating 
ON denormalized_chat(last_message_with_content_and_not_rating_or_forward);

-- Index #23
CREATE INDEX idx_denormalized_chat_last_message_timestamp_no_rating 
ON denormalized_chat(last_message_with_not_rating_or_forward_events_timestamp);

-- Index #24
CREATE EXTENSION IF NOT EXISTS pg_trgm;
CREATE INDEX idx_denormalized_chat_text_search
ON denormalized_chat USING gin (
    customer_support_display_name gin_trgm_ops, 
    end_user_first_name gin_trgm_ops,
    contacts_message gin_trgm_ops,
    comment gin_trgm_ops,
    status gin_trgm_ops,
    last_message_event gin_trgm_ops,
    chat_id gin_trgm_ops,
    last_message gin_trgm_ops
);

-- Index #25
-- First, create a custom immutable function
CREATE OR REPLACE FUNCTION immutable_array_to_string(text[], text) RETURNS text
    LANGUAGE sql IMMUTABLE
    AS '
    SELECT array_to_string($1, $2);
';

-- Then create the index using this function
CREATE INDEX idx_denormalized_chat_all_messages_text_search
ON denormalized_chat USING gin (
    immutable_array_to_string(all_messages, ' ') gin_trgm_ops
);


-- Uncomment and test perfomrance if list_chats_cs_ended query becomes slow:
-- Create GIN trigram indexes for each ILIKE searchable field
-- CREATE INDEX idx_denorm_chat_support_display_name_trgm ON chat.denormalized_chat USING GIN (customer_support_display_name gin_trgm_ops);
-- CREATE INDEX idx_denorm_chat_end_user_first_name_trgm ON chat.denormalized_chat USING GIN (end_user_first_name gin_trgm_ops);
-- CREATE INDEX idx_denorm_chat_contacts_message_trgm ON chat.denormalized_chat USING GIN (contacts_message gin_trgm_ops);
-- CREATE INDEX idx_denorm_chat_comment_trgm ON chat.denormalized_chat USING GIN (comment gin_trgm_ops);
-- CREATE INDEX idx_denorm_chat_last_message_trgm ON chat.denormalized_chat USING GIN (last_message gin_trgm_ops);
-- CREATE INDEX idx_denorm_chat_chat_id_trgm ON chat.denormalized_chat USING GIN (chat_id gin_trgm_ops);
-- CREATE INDEX idx_denorm_chat_first_msg_formatted ON chat.denormalized_chat USING GIN (TO_CHAR(first_message_timestamp, 'DD.MM.YYYY HH24:MI:SS') gin_trgm_ops);
-- CREATE INDEX idx_denorm_chat_ended_formatted ON chat.denormalized_chat USING GIN (TO_CHAR(ended, 'DD.MM.YYYY HH24:MI:SS') gin_trgm_ops);

-- Updated INSERT script to include both IDLE and non-IDLE chats
INSERT INTO denormalized_chat (
    chat_id,
    customer_support_id,
    customer_support_display_name,
    customer_support_first_name,
    customer_support_last_name,
    end_user_id,
    end_user_first_name,
    end_user_last_name,
    end_user_email,
    end_user_phone,
    end_user_os,
    end_user_url,
    status,
    first_message_timestamp,
    last_message_author_id,
    created,
    updated,
    denormalized_record_created,
    ended,
    forwarded_to,
    forwarded_to_name,
    received_from,
    received_from_name,
    external_id,
    labels,
    comment,
    comment_added_date,
    comment_author,
    first_message,
    last_message,
    last_message_including_empty_content,
    contacts_message,
    last_message_timestamp,
    feedback_text,
    feedback_rating,
    csa_title,
    last_message_event,
    last_message_event_with_content,
    chat_duration_in_seconds,
    first_support_timestamp,
    customer_messages_count,
    -- New columns
    last_message_with_content_and_not_rating_or_forward,
    last_message_with_not_rating_or_forward_events_timestamp,
    last_non_empty_message_event,
    all_messages
)
WITH 
latest_chats AS (
    SELECT c.id, c.base_id, c.updated
    FROM chat c
    INNER JOIN (
        SELECT base_id, MAX(id) as max_id
        FROM chat
        GROUP BY base_id
    ) latest ON c.base_id = latest.base_id AND c.id = latest.max_id
),
latest_messages AS (
    SELECT m.id, m.chat_base_id AS base_id, m.updated
    FROM message m
    INNER JOIN (
        SELECT chat_base_id, MAX(id) as max_id
        FROM message
        GROUP BY chat_base_id
    ) latest ON m.chat_base_id = latest.chat_base_id AND m.id = latest.max_id
),
latest_chcs AS (
    SELECT chc.id, chc.chat_id AS base_id, chc.created
    FROM chat_history_comments chc
    INNER JOIN (
        SELECT chat_id, MAX(id) as max_id
        FROM chat_history_comments
        GROUP BY chat_id
    ) latest ON chc.chat_id = latest.chat_id AND chc.id = latest.max_id
),
combined_records AS (
    -- Including original ended chats records
    -- Chat history comment records for ended chats
    SELECT
        chc.created AS record_date,
        chc.id AS chat_history_id,
        chc.chat_id,
        chc.comment,
        chc.created AS comment_added_date,
        chc.author_display_name AS comment_author,
        m.min_id,
        m.max_id,
        m.first_message_content,
        m.max_msg_updated AS last_message_timestamp,
        m.max_msg_event AS last_message_event,
        m.max_msg_event_with_content AS last_message_event_with_content,
        m.last_message_content,
        m.last_message_including_empty_content,
        m.customer_messages_count,
        cm.contact_message_content,
        c.customer_support_id,
        m.max_msg_author_id AS author_id,
        c.customer_support_display_name,
        cu.first_name AS customer_support_first_name,
        cu.last_name AS customer_support_last_name,
        c.csa_title,
        c.end_user_id,
        c.end_user_first_name,
        c.end_user_last_name,
        c.end_user_email,
        c.end_user_phone,
        c.end_user_os,
        c.end_user_url,
        c.status,
        c.updated AS chat_updated,
        c.ended,
        c.forwarded_to,
        c.forwarded_to_name,
        c.received_from,
        c.received_from_name,
        c.external_id,
        c.labels,
        m.first_message_timestamp AS first_message_timestamp,
        c.created AS chat_created,
        c.feedback_text,
        c.feedback_rating,
        chc.created,
        fsm.first_support_timestamp,
        CASE
            WHEN fsm.first_support_timestamp IS NOT NULL AND lm.last_timestamp IS NOT NULL
            THEN ABS(EXTRACT(EPOCH FROM (fsm.first_support_timestamp - lm.last_timestamp)))
            ELSE NULL
        END AS duration_seconds,
        -- New columns data
        m.last_message_content_no_rating_forward,
        m.last_message_timestamp_no_rating_forward,
        m.last_non_empty_message_event,
        (
            SELECT array_agg(content ORDER BY id) AS all_message_contents
            FROM message
            WHERE chat_base_id = chc.chat_id
            and content <> ''
        ) AS all_messages
    FROM
        chat_history_comments AS chc
    LEFT JOIN LATERAL (
        SELECT *
        FROM chat AS c
        WHERE c.base_id = chc.chat_id
        ORDER BY c.updated DESC
        LIMIT 1
    ) AS c ON true
    LEFT JOIN LATERAL (
        WITH content_message_bounds AS (
            SELECT
                MAX(id) AS max_content_id,
                MIN(id) AS min_content_id
            FROM message AS m
            WHERE
                m.chat_base_id = chc.chat_id
                AND content <> ''
                AND content <> 'message-read'
        ),
        all_message_bounds AS (
            SELECT
                MAX(id) AS max_id
            FROM message AS m
            WHERE
                m.chat_base_id = chc.chat_id
        ),
        customer_messages_count AS (
            SELECT COUNT(inner_m.id) AS customer_messages_count
            FROM message AS inner_m
            WHERE
                inner_m.chat_base_id = chc.chat_id
                AND inner_m.author_role = 'end-user'
                AND (inner_m.event = '' OR inner_m.event IS NULL)
        ),
        -- Add CTEs for new columns
        content_not_rating_forward_message AS (
            SELECT 
                MAX(id) AS max_content_not_rating_forward_id
            FROM message AS m
            WHERE
                m.chat_base_id = chc.chat_id
                AND m.content <> ''
                AND m.content <> 'message-read'
                AND m.event <> 'rating'
                AND m.event <> 'requested-chat-forward'
        ),
        not_rating_forward_message AS (
            SELECT 
                MAX(id) AS max_not_rating_forward_id
            FROM message AS m
            WHERE
                m.chat_base_id = chc.chat_id
                AND m.event <> 'rating'
                AND m.event <> 'requested-chat-forward'
        ),
        non_empty_event_message AS (
            SELECT 
                MAX(id) AS max_non_empty_event_id
            FROM message AS m
            WHERE
                m.chat_base_id = chc.chat_id
                AND m.event <> ''
                AND m.event IS NOT NULL
        )
        SELECT
            cmb.min_content_id AS min_id,
            cmb.max_content_id AS max_id,
            min_msg.created AS first_message_timestamp,
            min_msg.content AS first_message_content,
            max_content_msg.content AS last_message_content,
            max_msg.content AS last_message_including_empty_content,
            max_msg.updated AS max_msg_updated,
            max_msg.event AS max_msg_event,
            max_content_msg.event AS max_msg_event_with_content,
            max_msg.author_id AS max_msg_author_id,
            cmc.customer_messages_count,
            -- Get data for new columns
            content_not_rating_msg.content AS last_message_content_no_rating_forward,
            not_rating_msg.updated AS last_message_timestamp_no_rating_forward,
            non_empty_msg.event AS last_non_empty_message_event
        FROM content_message_bounds AS cmb
        CROSS JOIN all_message_bounds AS amb
        CROSS JOIN customer_messages_count AS cmc
        LEFT JOIN message AS min_msg ON min_msg.id = cmb.min_content_id
        LEFT JOIN message AS max_content_msg ON max_content_msg.id = cmb.max_content_id
        LEFT JOIN message AS max_msg ON max_msg.id = amb.max_id
        -- Join tables for new columns
        LEFT JOIN content_not_rating_forward_message AS crf ON TRUE
        LEFT JOIN message AS content_not_rating_msg ON content_not_rating_msg.id = crf.max_content_not_rating_forward_id
        LEFT JOIN not_rating_forward_message AS nrf ON TRUE
        LEFT JOIN message AS not_rating_msg ON not_rating_msg.id = nrf.max_not_rating_forward_id
        LEFT JOIN non_empty_event_message AS nem ON TRUE
        LEFT JOIN message AS non_empty_msg ON non_empty_msg.id = nem.max_non_empty_event_id
    ) AS m ON TRUE
    LEFT JOIN LATERAL (
        SELECT
            m.content AS contact_message_content
        FROM message AS m
        WHERE m.chat_base_id = chc.chat_id
        AND m.event = 'contact-information-fulfilled'
        ORDER BY m.id DESC
        LIMIT 1
    ) AS cm ON TRUE
    LEFT JOIN LATERAL (
        SELECT
            first_name,
            last_name
        FROM "user" AS u
        WHERE u.id_code = c.customer_support_id
        ORDER BY u.created DESC
        LIMIT 1
    ) AS cu ON TRUE
    LEFT JOIN LATERAL (
        SELECT
            chat_base_id,
            MIN(author_timestamp) AS first_support_timestamp
        FROM message
        WHERE
            chat_base_id = chc.chat_id
            AND author_role = 'backoffice-user'
        GROUP BY chat_base_id
    ) AS fsm ON TRUE    
    LEFT JOIN LATERAL (
        SELECT
            chat_base_id,
            MAX(author_timestamp) AS last_timestamp
        FROM message
        WHERE
            chat_base_id = chc.chat_id
        GROUP BY chat_base_id
    ) AS lm ON TRUE
    WHERE c.base_id IS NOT NULL
    AND NOT EXISTS (
        SELECT 1
        FROM chat_history_comments AS chc_inner
        WHERE chc_inner.chat_id = chc.chat_id
        AND chc_inner.created = chc.created
        AND chc_inner.id < chc.id
    )
    AND chc.id IN (select latest_chcs.id from latest_chcs where base_id = chc.chat_id)
    AND (
        chc.created > COALESCE((SELECT MAX(updated) FROM latest_chats WHERE base_id = chc.chat_id), '1900-01-01'::timestamp)
        AND chc.created > COALESCE((SELECT MAX(updated) FROM latest_messages WHERE base_id = chc.chat_id), '1900-01-01'::timestamp)
    )

    UNION ALL

    -- Chat records without matching history comments (for ended chats)
    SELECT
        c.updated AS record_date,
        chc_latest.id AS chat_history_id,
        c.base_id AS chat_id,
        chc_latest.comment,
        chc_latest.created AS comment_added_date,
        chc_latest.author_display_name AS comment_author,
        m.min_id,
        m.max_id,
        m.first_message_content,
        m.max_msg_updated AS last_message_timestamp,
        m.max_msg_event AS last_message_event,
        m.max_msg_event_with_content AS last_message_event_with_content,
        m.last_message_content,
        m.last_message_including_empty_content,
        m.customer_messages_count,
        cm.contact_message_content,
        c.customer_support_id,
        m.max_msg_author_id AS author_id,
        c.customer_support_display_name,
        cu.first_name AS customer_support_first_name,
        cu.last_name AS customer_support_last_name,
        c.csa_title,
        c.end_user_id,
        c.end_user_first_name,
        c.end_user_last_name,
        c.end_user_email,
        c.end_user_phone,
        c.end_user_os,
        c.end_user_url,
        c.status,
        c.updated AS chat_updated,
        c.ended,
        c.forwarded_to,
        c.forwarded_to_name,
        c.received_from,
        c.received_from_name,
        c.external_id,
        c.labels,
        m.first_message_timestamp AS first_message_timestamp,
        c.created AS chat_created,
        c.feedback_text,
        c.feedback_rating,
        c.created,
        fsm.first_support_timestamp,
        CASE
            WHEN fsm.first_support_timestamp IS NOT NULL AND lm.last_timestamp IS NOT NULL
            THEN ABS(EXTRACT(EPOCH FROM (fsm.first_support_timestamp - lm.last_timestamp)))
            ELSE NULL
        END AS duration_seconds,
        -- New columns data
        m.last_message_content_no_rating_forward,
        m.last_message_timestamp_no_rating_forward,
        m.last_non_empty_message_event,
        (
            SELECT array_agg(content ORDER BY id) AS all_message_contents
            FROM message
            WHERE chat_base_id = c.base_id
            and content <> ''
        ) AS all_messages
    FROM
        chat AS c
    LEFT JOIN LATERAL (
        SELECT *
        FROM chat_history_comments AS chc
        WHERE chc.chat_id = c.base_id
        ORDER BY chc.created DESC
        LIMIT 1
    ) AS chc_latest ON true
    LEFT JOIN LATERAL (
        WITH content_message_bounds AS (
            SELECT
                MAX(id) AS max_content_id,
                MIN(id) AS min_content_id
            FROM message AS m
            WHERE
                m.chat_base_id = c.base_id
                AND content <> ''
                AND content <> 'message-read'
        ),
        all_message_bounds AS (
            SELECT
                MAX(id) AS max_id
            FROM message AS m
            WHERE
                m.chat_base_id = c.base_id
        ),
        customer_messages_count AS (
            SELECT COUNT(inner_m.id) AS customer_messages_count
            FROM message AS inner_m
            WHERE
                inner_m.chat_base_id = c.base_id
                AND inner_m.author_role = 'end-user'
                AND (inner_m.event = '' OR inner_m.event IS NULL)
        ),
        -- Add CTEs for new columns
        content_not_rating_forward_message AS (
            SELECT 
                MAX(id) AS max_content_not_rating_forward_id
            FROM message AS m
            WHERE
                m.chat_base_id = c.base_id
                AND m.content <> ''
                AND m.content <> 'message-read'
                AND m.event <> 'rating'
                AND m.event <> 'requested-chat-forward'
        ),
        not_rating_forward_message AS (
            SELECT 
                MAX(id) AS max_not_rating_forward_id
            FROM message AS m
            WHERE
                m.chat_base_id = c.base_id
                AND m.event <> 'rating'
                AND m.event <> 'requested-chat-forward'
        ),
        non_empty_event_message AS (
            SELECT 
                MAX(id) AS max_non_empty_event_id
            FROM message AS m
            WHERE
                m.chat_base_id = c.base_id
                AND m.event <> ''
                AND m.event IS NOT NULL
        )
        SELECT
            cmb.min_content_id AS min_id,
            cmb.max_content_id AS max_id,
            min_msg.content AS first_message_content,
            min_msg.created AS first_message_timestamp,
            max_content_msg.content AS last_message_content,
            max_msg.content AS last_message_including_empty_content,
            max_msg.updated AS max_msg_updated,
            max_msg.event AS max_msg_event,
            max_content_msg.event AS max_msg_event_with_content,
            max_msg.author_id AS max_msg_author_id,
            cmc.customer_messages_count,
            -- Get data for new columns
            content_not_rating_msg.content AS last_message_content_no_rating_forward,
            not_rating_msg.updated AS last_message_timestamp_no_rating_forward,
            non_empty_msg.event AS last_non_empty_message_event
        FROM content_message_bounds AS cmb
        CROSS JOIN all_message_bounds AS amb
        CROSS JOIN customer_messages_count AS cmc
        LEFT JOIN message AS min_msg ON min_msg.id = cmb.min_content_id
        LEFT JOIN message AS max_content_msg ON max_content_msg.id = cmb.max_content_id
        LEFT JOIN message AS max_msg ON max_msg.id = amb.max_id
        -- Join tables for new columns
        LEFT JOIN content_not_rating_forward_message AS crf ON TRUE
        LEFT JOIN message AS content_not_rating_msg ON content_not_rating_msg.id = crf.max_content_not_rating_forward_id
        LEFT JOIN not_rating_forward_message AS nrf ON TRUE
        LEFT JOIN message AS not_rating_msg ON not_rating_msg.id = nrf.max_not_rating_forward_id
        LEFT JOIN non_empty_event_message AS nem ON TRUE
        LEFT JOIN message AS non_empty_msg ON non_empty_msg.id = nem.max_non_empty_event_id
    ) AS m ON TRUE
    LEFT JOIN LATERAL (
        SELECT
            m.content AS contact_message_content
        FROM message AS m
        WHERE m.chat_base_id = c.base_id
        AND m.event = 'contact-information-fulfilled'
        ORDER BY m.id DESC
        LIMIT 1
    ) AS cm ON TRUE
    LEFT JOIN LATERAL (
        SELECT
            first_name,
            last_name
        FROM "user" AS u
        WHERE u.id_code = c.customer_support_id
        ORDER BY u.created DESC
        LIMIT 1
    ) AS cu ON TRUE
    LEFT JOIN LATERAL (
        SELECT
            chat_base_id,
            MIN(author_timestamp) AS first_support_timestamp
        FROM message
        WHERE
            chat_base_id = c.base_id
            AND author_role = 'backoffice-user'
        GROUP BY chat_base_id
    ) AS fsm ON TRUE
    LEFT JOIN LATERAL (
        SELECT
            chat_base_id,
            MAX(author_timestamp) AS last_timestamp
        FROM message
        WHERE
            chat_base_id = c.base_id
        GROUP BY chat_base_id
    ) AS lm ON TRUE
    WHERE NOT EXISTS (
        SELECT 1
        FROM chat_history_comments AS chc
        WHERE chc.chat_id = c.base_id
    )
    AND c.id IN (select latest_chats.id from latest_chats where base_id = c.base_id)
    AND (
        c.updated > COALESCE((SELECT MAX(updated) FROM latest_messages WHERE base_id = c.base_id), '1900-01-01'::timestamp)
    )

    UNION ALL

    -- Message records without matching chats or history comments
    SELECT
        m.updated AS record_date,
        chc_latest.id AS chat_history_id,
        m.chat_base_id AS chat_id,
        chc_latest.comment,
        chc_latest.created AS comment_added_date,
        chc_latest.author_display_name AS comment_author,
        m_bounds.min_id,
        m_bounds.max_id,
        m_msg.content AS first_message_content,
        m.updated AS last_message_timestamp,
        m.event AS last_message_event,
        CASE
            WHEN m.content <> '' AND m.content <> 'message-read' THEN m.event
            ELSE NULL
        END AS last_message_event_with_content,
        CASE
            WHEN m.content <> '' AND m.content <> 'message-read' THEN m.content
            ELSE (SELECT content
                FROM message
                WHERE chat_base_id = m.chat_base_id
                AND content <> ''
                AND content <> 'message-read'
                ORDER BY id DESC
                LIMIT 1)
        END AS last_message_content,
        m.content AS last_message_including_empty_content,
        cmc.customer_messages_count,
        cm.contact_message_content,
        c.customer_support_id,
        m.author_id,
        c.customer_support_display_name,
        cu.first_name AS customer_support_first_name,
        cu.last_name AS customer_support_last_name,
        c.csa_title,
        c.end_user_id,
        c.end_user_first_name,
        c.end_user_last_name,
        c.end_user_email,
        c.end_user_phone,
        c.end_user_os,
        c.end_user_url,
        c.status,
        c.updated AS chat_updated,
        c.ended,
        c.forwarded_to,
        c.forwarded_to_name,
        c.received_from,
        c.received_from_name,
        c.external_id,
        c.labels,
        m_msg.created AS first_message_timestamp,
        c.created AS chat_created,
        c.feedback_text,
        c.feedback_rating,
        m.created,
        fsm.first_support_timestamp,
        CASE
            WHEN fsm.first_support_timestamp IS NOT NULL AND lm.last_timestamp IS NOT NULL
            THEN ABS(EXTRACT(EPOCH FROM (fsm.first_support_timestamp - lm.last_timestamp)))
            ELSE NULL
        END AS duration_seconds,
        -- New columns data
        (SELECT content
         FROM message
         WHERE chat_base_id = m.chat_base_id
         AND content <> ''
         AND content <> 'message-read'
         AND event <> 'rating'
         AND event <> 'requested-chat-forward'
         ORDER BY id DESC
         LIMIT 1) AS last_message_content_no_rating_forward,
        (SELECT updated
         FROM message
         WHERE chat_base_id = m.chat_base_id
         AND event <> 'rating'
         AND event <> 'requested-chat-forward'
         ORDER BY id DESC
         LIMIT 1) AS last_message_timestamp_no_rating_forward,
        (SELECT event
         FROM message
         WHERE chat_base_id = m.chat_base_id
         AND event <> ''
         AND event IS NOT NULL
         ORDER BY id DESC
         LIMIT 1) AS last_non_empty_message_event,
         (
            SELECT array_agg(content ORDER BY id) AS all_message_contents
            FROM message
            WHERE chat_base_id = m.chat_base_id
            and content <> ''
        ) AS all_messages
    FROM
        message AS m
    LEFT JOIN LATERAL (
        SELECT *
        FROM chat_history_comments AS chc
        WHERE chc.chat_id = m.chat_base_id
        ORDER BY chc.created DESC
        LIMIT 1
    ) AS chc_latest ON true
    LEFT JOIN LATERAL (
        SELECT *
        FROM chat AS c
        WHERE c.base_id = m.chat_base_id
        ORDER BY c.updated DESC
        LIMIT 1
    ) AS c ON true
    LEFT JOIN LATERAL (
        WITH message_bounds AS (
            SELECT
                MIN(id) AS min_id
            FROM message AS inner_m
            WHERE
                inner_m.chat_base_id = m.chat_base_id
                AND inner_m.content <> ''
                AND inner_m.content <> 'message-read'
        )
        SELECT
            mb.min_id,
            m.id AS max_id
        FROM message_bounds AS mb
    ) AS m_bounds ON TRUE
    LEFT JOIN message AS m_msg ON m_msg.id = m_bounds.min_id
    LEFT JOIN LATERAL (
        SELECT COUNT(inner_m.id) AS customer_messages_count
        FROM message AS inner_m
        WHERE
            inner_m.chat_base_id = m.chat_base_id
            AND inner_m.author_role = 'end-user'
            AND (inner_m.event = '' OR inner_m.event IS NULL)
    ) AS cmc ON TRUE
    LEFT JOIN LATERAL (
        SELECT
            m_cm.content AS contact_message_content
        FROM message AS m_cm
        WHERE m_cm.chat_base_id = m.chat_base_id
        AND m_cm.event = 'contact-information-fulfilled'
        ORDER BY m_cm.id DESC
        LIMIT 1
    ) AS cm ON TRUE
    LEFT JOIN LATERAL (
        SELECT
            first_name,
            last_name
        FROM "user" AS u
        WHERE u.id_code = c.customer_support_id
        ORDER BY u.created DESC
        LIMIT 1
    ) AS cu ON TRUE
    LEFT JOIN LATERAL (
        SELECT
            chat_base_id,
            MIN(author_timestamp) AS first_support_timestamp
        FROM message
        WHERE
            chat_base_id = m.chat_base_id
            AND author_role = 'backoffice-user'
        GROUP BY chat_base_id
    ) AS fsm ON TRUE
    LEFT JOIN LATERAL (
        SELECT
            chat_base_id,
            MAX(author_timestamp) AS last_timestamp
        FROM message
        WHERE
            chat_base_id = m.chat_base_id
        GROUP BY chat_base_id
    ) AS lm ON TRUE
    WHERE c.base_id IS NOT NULL
    AND NOT EXISTS (
        SELECT 1
        FROM chat_history_comments AS chc
        WHERE chc.chat_id = m.chat_base_id
        AND chc.created = m.updated
    )
    AND NOT EXISTS (
        SELECT 1
        FROM chat AS cx
        WHERE cx.base_id = m.chat_base_id
        AND cx.updated = m.updated
    )
    AND m.id IN (select latest_messages.id from latest_messages where latest_messages.base_id = m.chat_base_id)
    AND (
        m.updated > COALESCE((SELECT MAX(updated) FROM latest_chats WHERE base_id = m.chat_base_id), '1900-01-01'::timestamp)
    )
)
SELECT
    chat_id,
    customer_support_id,
    customer_support_display_name,
    customer_support_first_name,
    customer_support_last_name,
    end_user_id,
    end_user_first_name,
    end_user_last_name,
    end_user_email,
    end_user_phone,
    end_user_os,
    end_user_url,
    status,
    first_message_timestamp,
    author_id,
    chat_created AS created,
    chat_updated AS updated,
    record_date AS denormalized_record_created,
    ended,
    forwarded_to,
    forwarded_to_name,
    received_from,
    received_from_name,
    external_id,
    labels,
    comment,
    comment_added_date,
    comment_author,
    first_message_content AS first_message,
    last_message_content AS last_message,
    last_message_including_empty_content,
    contact_message_content AS contacts_message,
    last_message_timestamp,
    feedback_text,
    feedback_rating,
    csa_title,
    CASE
        WHEN last_message_event IS NULL THEN NULL
        ELSE LOWER(last_message_event)
    END AS last_message_event,
    CASE
        WHEN last_message_event_with_content IS NULL THEN NULL
        ELSE LOWER(last_message_event_with_content)
    END AS last_message_event_with_content,
    duration_seconds AS chat_duration_in_seconds,
    first_support_timestamp,
    customer_messages_count,
    -- New columns
    last_message_content_no_rating_forward AS last_message_with_content_and_not_rating_or_forward,
    last_message_timestamp_no_rating_forward AS last_message_with_not_rating_or_forward_events_timestamp,
    CASE
        WHEN last_non_empty_message_event IS NULL THEN NULL
        ELSE LOWER(last_non_empty_message_event)
    END AS last_non_empty_message_event,
    all_messages
FROM combined_records
WHERE chat_id IN (SELECT base_id FROM chat)
ORDER BY denormalized_record_created;
