-- liquibase formatted sql
-- changeset igor:20260204141717
CREATE TABLE IF NOT EXISTS attachment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    base_id VARCHAR(36) NOT NULL UNIQUE,
    chat_base_id VARCHAR(36) NOT NULL,
    message_base_id VARCHAR(36),
    file_name VARCHAR(255) NOT NULL,
    file_size BIGINT NOT NULL,
    mime_type VARCHAR(128) NOT NULL,
    storage_path VARCHAR(512) NOT NULL,
    uploaded_by VARCHAR(555) NOT NULL,
    uploaded_by_role VARCHAR(128) NOT NULL,
    status VARCHAR(128) NOT NULL DEFAULT 'available',
    created TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX idx_attachment_chat_base_id ON attachment (chat_base_id);

CREATE INDEX idx_attachment_base_id ON attachment (base_id);

CREATE INDEX idx_attachment_status ON attachment (status);

CREATE INDEX idx_attachment_created ON attachment (created);