-- liquibase formatted sql
-- changeset Igor Krupenja:20260204111034

CREATE TABLE IF NOT EXISTS attachment (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    base_id VARCHAR(36) NOT NULL,
    chat_base_id VARCHAR(36) NOT NULL,
    message_base_id VARCHAR(36),
    file_name VARCHAR(255) NOT NULL,
    file_size BIGINT NOT NULL,
    mime_type VARCHAR(100) NOT NULL,
    s3_bucket VARCHAR(100) NOT NULL DEFAULT 'quarantine',
    s3_key VARCHAR(500) NOT NULL,
    uploaded_by_user_id VARCHAR(255),
    uploaded_by_role VARCHAR(50) NOT NULL CHECK (uploaded_by_role IN ('end-user', 'backoffice-user')),
    status VARCHAR(50) NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'uploaded', 'available', 'failed')),
    created TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Index for faster lookups by base_id
CREATE INDEX idx_attachment_base_id ON attachment(base_id);

-- Index for faster lookups by chat
CREATE INDEX idx_attachment_chat_base_id ON attachment(chat_base_id);

-- Index for faster lookups by message
CREATE INDEX idx_attachment_message_base_id ON attachment(message_base_id);

-- Index for faster lookups by status
CREATE INDEX idx_attachment_status ON attachment(status);
