-- liquibase formatted sql

-- changeset liquibase:1719279300826
CREATE TYPE user_status AS ENUM ('active','deleted');

CREATE TYPE status AS ENUM ('online','idle', 'offline');

CREATE EXTENSION IF NOT EXISTS hstore;

CREATE TABLE "configuration" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, "key" VARCHAR(128), "value" VARCHAR(128), "deleted" BOOLEAN DEFAULT FALSE NOT NULL, "created" TIMESTAMP WITH TIME ZONE, CONSTRAINT "configuration_pkey" PRIMARY KEY ("id"));

INSERT INTO "configuration" ("id", "key", "value", "deleted", "created") VALUES (1, 'is_csa_name_visible', 'true', FALSE, NULL);
INSERT INTO "configuration" ("id", "key", "value", "deleted", "created") VALUES (2, 'is_csa_title_visible', 'true', FALSE, NULL);
INSERT INTO "configuration" ("id", "key", "value", "deleted", "created") VALUES (3, 'widgetProactiveSeconds', '3', FALSE, NULL);
INSERT INTO "configuration" ("id", "key", "value", "deleted", "created") VALUES (4, 'widgetDisplayBubbleMessageSeconds', '5', FALSE, NULL);
INSERT INTO "configuration" ("id", "key", "value", "deleted", "created") VALUES (5, 'widgetBubbleMessageText', 'Küsi minult!', FALSE, NULL);
INSERT INTO "configuration" ("id", "key", "value", "deleted", "created") VALUES (6, 'widgetColor', '#003cff', FALSE, NULL);
INSERT INTO "configuration" ("id", "key", "value", "deleted", "created") VALUES (7, 'isWidgetActive', 'true', FALSE, NULL);
INSERT INTO "configuration" ("id", "key", "value", "deleted", "created") VALUES (8, 'end_user_session_length', '120', FALSE, NULL);
INSERT INTO "configuration" ("id", "key", "value", "deleted", "created") VALUES (9, 'session_length', '120', FALSE, NULL);
INSERT INTO "configuration" ("id", "key", "value", "deleted", "created") VALUES (10, 'estimated_waiting_time', '120', FALSE, NULL);
INSERT INTO "configuration" ("id", "key", "value", "deleted", "created") VALUES (11, 'is_bot_active', 'true', FALSE, NULL);
INSERT INTO "configuration" ("id", "key", "value", "deleted", "created") VALUES (12, 'end_user_session_length', '120', FALSE, NULL);
INSERT INTO "configuration" ("id", "key", "value", "deleted", "created") VALUES (13, 'is_csa_name_visible', 'true', FALSE, NULL);
INSERT INTO "configuration" ("id", "key", "value", "deleted", "created") VALUES (14, 'is_csa_title_visible', 'true', FALSE, NULL);
INSERT INTO "configuration" ("id", "key", "value", "deleted", "created") VALUES (15, 'is_estimated_waiting_time_active', 'true', FALSE, NULL);
INSERT INTO "configuration" ("id", "key", "value", "deleted", "created") VALUES (16, 'bot_institution_id', 'chatbot', FALSE, NULL);
INSERT INTO "configuration" ("id", "key", "value", "deleted", "created") VALUES (17, 'is_greeting_message_active', 'true', FALSE, NULL);
INSERT INTO "configuration" ("id", "key", "value", "deleted", "created") VALUES (18, 'greeting_message_est', 'tere', FALSE, NULL);
INSERT INTO "configuration" ("id", "key", "value", "deleted", "created") VALUES (19, 'emergencyNoticeText', 'We are out of service at the moment', FALSE, NULL);
INSERT INTO "configuration" ("id", "key", "value", "deleted", "created") VALUES (20, 'emergencyNoticeStartISO', '2023-10-22T23:00:00.000Z', FALSE, NULL);
INSERT INTO "configuration" ("id", "key", "value", "deleted", "created") VALUES (21, 'emergencyNoticeEndISO', '2023-10-22T22:00:00.000Z', FALSE, NULL);
INSERT INTO "configuration" ("id", "key", "value", "deleted", "created") VALUES (22, 'isEmergencyNoticeVisible', 'false', FALSE, NULL);
INSERT INTO "configuration" ("id", "key", "value", "deleted", "created") VALUES (23, 'organizationMondayWorkingTimeStartISO', '2023-10-22T09:00:00.000Z', FALSE, NULL);
INSERT INTO "configuration" ("id", "key", "value", "deleted", "created") VALUES (24, 'organizationMondayWorkingTimeEndISO', '2023-10-22T17:00:00.000Z', FALSE, NULL);
INSERT INTO "configuration" ("id", "key", "value", "deleted", "created") VALUES (25, 'organizationTuesdayWorkingTimeStartISO', '2023-10-22T09:00:00.000Z', FALSE, NULL);
INSERT INTO "configuration" ("id", "key", "value", "deleted", "created") VALUES (26, 'organizationTuesdayWorkingTimeEndISO', '2023-10-22T17:00:00.000Z', FALSE, NULL);
INSERT INTO "configuration" ("id", "key", "value", "deleted", "created") VALUES (27, 'organizationWednesdayWorkingTimeStartISO', '2023-10-22T09:00:00.000Z', FALSE, NULL);
INSERT INTO "configuration" ("id", "key", "value", "deleted", "created") VALUES (28, 'organizationWednesdayWorkingTimeEndISO', '2023-10-22T17:00:00.000Z', FALSE, NULL);
INSERT INTO "configuration" ("id", "key", "value", "deleted", "created") VALUES (29, 'organizationThursdayWorkingTimeStartISO', '2023-10-22T09:00:00.000Z', FALSE, NULL);
INSERT INTO "configuration" ("id", "key", "value", "deleted", "created") VALUES (30, 'organizationThursdayWorkingTimeEndISO', '2023-10-22T17:00:00.000Z', FALSE, NULL);
INSERT INTO "configuration" ("id", "key", "value", "deleted", "created") VALUES (31, 'organizationFridayWorkingTimeStartISO', '2023-10-22T09:00:00.000Z', FALSE, NULL);
INSERT INTO "configuration" ("id", "key", "value", "deleted", "created") VALUES (32, 'organizationFridayWorkingTimeEndISO', '2023-10-22T17:00:00.000Z', FALSE, NULL);
INSERT INTO "configuration" ("id", "key", "value", "deleted", "created") VALUES (33, 'organizationSaturdayWorkingTimeStartISO', '2023-10-22T09:00:00.000Z', FALSE, NULL);
INSERT INTO "configuration" ("id", "key", "value", "deleted", "created") VALUES (34, 'organizationSaturdayWorkingTimeEndISO', '2023-10-22T17:00:00.000Z', FALSE, NULL);
INSERT INTO "configuration" ("id", "key", "value", "deleted", "created") VALUES (35, 'organizationSundayWorkingTimeStartISO', '2023-10-22T09:00:00.000Z', FALSE, NULL);
INSERT INTO "configuration" ("id", "key", "value", "deleted", "created") VALUES (36, 'organizationSundayWorkingTimeEndISO', '2023-10-22T17:00:00.000Z', FALSE, NULL);
INSERT INTO "configuration" ("id", "key", "value", "deleted", "created") VALUES (37, 'organizationAllWeekdaysTimeStartISO', '2023-10-22T09:00:00.000Z', FALSE, NULL);
INSERT INTO "configuration" ("id", "key", "value", "deleted", "created") VALUES (38, 'organizationAllWeekdaysTimeEndISO', '2023-10-22T17:00:00.000Z', FALSE, NULL);
INSERT INTO "configuration" ("id", "key", "value", "deleted", "created") VALUES (39, 'organizationWorkingTimeWeekdays', 'monday,tuesday,wednesday,thursday,friday,saturday,sunday', FALSE, NULL);
INSERT INTO "configuration" ("id", "key", "value", "deleted", "created") VALUES (40, 'organizationWorkingTimeNationalHolidays', 'true', FALSE, NULL);
INSERT INTO "configuration" ("id", "key", "value", "deleted", "created") VALUES (41, 'organizationClosedOnWeekEnds', 'false', FALSE, NULL);
INSERT INTO "configuration" ("id", "key", "value", "deleted", "created") VALUES (42, 'organizationTheSameOnAllWorkingDays', 'false', FALSE, NULL);

CREATE TABLE "chat" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, "base_id" VARCHAR(36) NOT NULL, "customer_support_id" VARCHAR(555), "customer_support_display_name" VARCHAR(60), "end_user_id" VARCHAR(555), "end_user_first_name" VARCHAR(555), "end_user_last_name" VARCHAR(555), "status" VARCHAR(128) NOT NULL, "created" TIMESTAMP WITH TIME ZONE NOT NULL, "updated" TIMESTAMP WITH TIME ZONE DEFAULT NOW(), "ended" TIMESTAMP WITH TIME ZONE, "end_user_os" VARCHAR, "end_user_url" VARCHAR, "feedback_rating" INTEGER, "feedback_text" VARCHAR, "forwarded_to" VARCHAR, "received_from" VARCHAR, "external_id" VARCHAR, "forwarded_to_name" VARCHAR, "received_from_name" VARCHAR, "csa_title" VARCHAR, "labels" VARCHAR[], "end_user_email" VARCHAR DEFAULT '', "end_user_phone" VARCHAR DEFAULT '');

CREATE TABLE "message" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, "chat_base_id" VARCHAR(36) NOT NULL, "base_id" VARCHAR(36) NOT NULL, "content" VARCHAR(3000), "event" VARCHAR(128), "author_id" VARCHAR(555), "author_timestamp" TIMESTAMP WITH TIME ZONE, "author_first_name" VARCHAR(555), "author_last_name" VARCHAR(555), "author_role" VARCHAR(128), "rating" INTEGER, "created" TIMESTAMP WITH TIME ZONE NOT NULL, "updated" TIMESTAMP WITH TIME ZONE DEFAULT NOW(), "forwarded_by_user" VARCHAR(50), "forwarded_from_csa" VARCHAR(50), "forwarded_to_csa" VARCHAR(50), "buttons" TEXT);

CREATE TABLE "establishment" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, "name" VARCHAR, "url" VARCHAR, "base_id" VARCHAR(36), "deleted" BOOLEAN DEFAULT FALSE NOT NULL, "created" TIMESTAMP WITH TIME ZONE DEFAULT NOW(), CONSTRAINT "establishment_pkey" PRIMARY KEY ("id"));

CREATE TABLE "user_profile_settings" ("user_id" VARCHAR(50) NOT NULL, "forwarded_chat_popup_notifications" BOOLEAN DEFAULT FALSE, "forwarded_chat_sound_notifications" BOOLEAN DEFAULT TRUE, "forwarded_chat_email_notifications" BOOLEAN DEFAULT FALSE, "new_chat_popup_notifications" BOOLEAN DEFAULT FALSE, "new_chat_sound_notifications" BOOLEAN DEFAULT TRUE, "new_chat_email_notifications" BOOLEAN DEFAULT FALSE, "use_autocorrect" BOOLEAN DEFAULT TRUE, "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, CONSTRAINT "user_profile_settings_pkey" PRIMARY KEY ("id"));

CREATE TABLE "message_preview" ("chat_base_id" VARCHAR(36) NOT NULL, "content" VARCHAR(3000), "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL, CONSTRAINT "message_preview_pkey" PRIMARY KEY ("id"));

CREATE TABLE "user" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, "login" VARCHAR(50) NOT NULL, "password_hash" VARCHAR(60), "first_name" VARCHAR(50), "last_name" VARCHAR(50), "id_code" VARCHAR(50) NOT NULL, "display_name" VARCHAR(50), "status" USER_STATUS, "created" TIMESTAMP WITH TIME ZONE, "csa_title" VARCHAR, "csa_email" VARCHAR, CONSTRAINT "user_pkey" PRIMARY KEY ("id"));

CREATE INDEX "idx_configuration_key" ON "configuration"("key");

CREATE INDEX "idx_chat_base_id" ON "chat"("base_id");

ALTER TABLE "chat" ADD CONSTRAINT "chat_id_key" UNIQUE ("id");

CREATE INDEX "idx_message_chat_base_id" ON "message"("chat_base_id");

CREATE INDEX "idx_message_event" ON "message"("event");

ALTER TABLE "message" ADD CONSTRAINT "message_id_key" UNIQUE ("id");

CREATE TABLE "customer_support_agent_activity" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, "id_code" VARCHAR, "active" BOOLEAN DEFAULT FALSE, "created" TIMESTAMP WITH TIME ZONE, "status" STATUS);

CREATE TABLE "allowed_statuses" ("name" VARCHAR(50) NOT NULL, CONSTRAINT "allowed_statuses_pkey" PRIMARY KEY ("name"));

CREATE TABLE "authority" ("name" VARCHAR(50) NOT NULL, CONSTRAINT "authority_pkey" PRIMARY KEY ("name"));

CREATE TABLE "chat_history_comments" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, "chat_id" VARCHAR(36) NOT NULL, "comment" VARCHAR, CONSTRAINT "chat_history_comments_pkey" PRIMARY KEY ("id"));

CREATE TABLE "user_authority" ("user_id" VARCHAR(50) NOT NULL, "authority_name" VARCHAR[] NOT NULL, "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, "created" TIMESTAMP WITH TIME ZONE, CONSTRAINT "user_authority_pkey" PRIMARY KEY ("id"));

INSERT INTO "allowed_statuses" ("name") VALUES ('CLIENT_LEFT_WITH_ACCEPTED');
INSERT INTO "allowed_statuses" ("name") VALUES ('CLIENT_LEFT_WITH_NO_RESOLUTION');
INSERT INTO "allowed_statuses" ("name") VALUES ('CLIENT_LEFT_FOR_UNKNOWN_REASONS');
INSERT INTO "allowed_statuses" ("name") VALUES ('ACCEPTED');
INSERT INTO "allowed_statuses" ("name") VALUES ('HATE_SPEECH');
INSERT INTO "allowed_statuses" ("name") VALUES ('OTHER');
INSERT INTO "allowed_statuses" ("name") VALUES ('RESPONSE_SENT_TO_CLIENT_EMAIL');

INSERT INTO "authority" ("name") VALUES ('ROLE_ADMINISTRATOR');
INSERT INTO "authority" ("name") VALUES ('ROLE_SERVICE_MANAGER');
INSERT INTO "authority" ("name") VALUES ('ROLE_CUSTOMER_SUPPORT_AGENT');
INSERT INTO "authority" ("name") VALUES ('ROLE_CHATBOT_TRAINER');
INSERT INTO "authority" ("name") VALUES ('ROLE_ANALYST');
INSERT INTO "authority" ("name") VALUES ('ROLE_UNAUTHENTICATED');
