FROM node:lts AS build
WORKDIR /app
COPY ./package.json .
RUN npm install --legacy-peer-deps --mode=development
COPY . .
RUN ./node_modules/.bin/vite build --mode=development

FROM nginx:1.27.4-alpine
COPY --from=build /app /usr/share/nginx/html
#COPY ./nginx/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 3001
EXPOSE 80

ENV REACT_APP_ENABLE_HIDDEN_FEATURES TRUE

CMD ["nginx", "-g", "daemon off;"]
