FROM node:22.14.0-alpine AS image
WORKDIR /app
COPY ./package.json .

FROM image AS build
RUN npm install --legacy-peer-deps --mode=development
COPY . .
RUN ./node_modules/.bin/vite build --mode=development

EXPOSE 3001

ENV REACT_APP_ENABLE_HIDDEN_FEATURES TRUE

CMD ["npm", "run", "dev"]
