FROM node:lts AS build
WORKDIR /app
COPY ./package.json .
COPY ./exirain-header-0.0.27.tgz .
RUN npm install --legacy-peer-deps --mode=development
COPY . .
RUN ./node_modules/.bin/vite build --mode=development

FROM nginx:latest
COPY --from=build /app /usr/share/nginx/html
#COPY ./nginx/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 3001
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
