extractRequestData:
  assign:
    userId: ${incoming.body.userId}
  next: getUserSettings

getUserSettings:
  call: http.post
  args:
    url: "[#CHATBOT_RESQL]:[#CHATBOT_RESQL_PORT]/get-user-profile-settings"
    body:
      userId: ${userId}
  result: getUserSettingsResult
  next: validateUserSettingsResultExists

validateUserSettingsResultExists:
  switch:
    - condition: "${getUserSettingsResult.response.body.length > 0}"
      next: returnSuccess
  next: returnNotFound

returnSuccess:
  return: ${getUserSettingsResult.response.body}
  next: end

returnNotFound:
  return: "error: not found"
  next: end
