declaration:
  call: declare
  version: 0.1
  description: "Decription placeholder for 'END-USER-SESSION-LENGTH'"
  method: get
  accepts: json
  returns: json
  namespace: backoffice

getConfigurationValue:
  call: http.post
  args:
    url: "[#CHATBOT_RESQL]/get-configuration"
    body:
      key: "end_user_session_length"
  result: res

return_result:
  return: ${res.response.body[0]?.value}
  status: 200
