-- Create a temporary testing table with the same structure as the denormalized table
CREATE TEMPORARY TABLE temp_denorm_table (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login VARCHAR(50),
    first_name VARCHAR(50),
    last_name VARCHAR(50),
    id_code VARCHAR(50),
    display_name VARCHAR(50),
    csa_title VARCHAR,
    csa_email VARCHAR,
    department TEXT,
    authority_name VARCHAR [],
    user_status VARCHAR(20),
    status VARCHAR(20),
    active BOOLEAN,
    forwarded_chat_popup_notifications BOOLEAN,
    forwarded_chat_sound_notifications BOOLEAN,
    forwarded_chat_email_notifications BOOLEAN,
    new_chat_popup_notifications BOOLEAN,
    new_chat_sound_notifications BOOLEAN,
    new_chat_email_notifications BOOLEAN,
    use_autocorrect BOOLEAN,
    created TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Insert some test data
INSERT INTO temp_denorm_table (
    login, first_name, last_name, id_code, display_name,
    csa_title, csa_email, department, authority_name, user_status,
    status, active,
    forwarded_chat_popup_notifications, forwarded_chat_sound_notifications,
    forwarded_chat_email_notifications, new_chat_popup_notifications,
    new_chat_sound_notifications, new_chat_email_notifications, use_autocorrect,
    created
) VALUES
-- First user with multiple records to test "latest record" retrieval
(
    'user1', 'John', 'Doe', 'US001', 'John D.',
    'Support Agent', 'john@example.com', 'Support', ARRAY['ROLE_USER'], 'active',
    'online', TRUE,
    TRUE, TRUE, FALSE, TRUE, TRUE, FALSE, TRUE,
    CURRENT_TIMESTAMP - INTERVAL '3 days'
),

(
    'user1', 'John', 'Doe', 'US001', 'John D.',
    'Support Lead',
    'john@example.com',
    'Support',
    ARRAY['ROLE_USER', 'ROLE_SUPPORT'],
    'active',
    'online', TRUE,
    TRUE, TRUE, FALSE, TRUE, TRUE, FALSE, TRUE,
    CURRENT_TIMESTAMP - INTERVAL '1 day'
),

-- Second user with one record
(
    'user2', 'Jane', 'Smith', 'US002', 'Jane S.',
    'Manager', 'jane@example.com', 'Management', ARRAY['ROLE_MANAGER'], 'active',
    'away', TRUE,
    FALSE, TRUE, TRUE, FALSE, TRUE, TRUE, FALSE,
    CURRENT_TIMESTAMP - INTERVAL '2 days'
);

-- Display the initial data
SELECT 'Initial Data:' AS section;
SELECT * FROM temp_denorm_table
ORDER BY id;

-- Define test parameter values
DO $$
DECLARE
    test_id_code VARCHAR := 'US001';
    new_roles VARCHAR[] := ARRAY['ROLE_USER', 'ROLE_SUPPORT', 'ROLE_ADMIN'];
    test_timestamp TIMESTAMP WITH TIME ZONE := CURRENT_TIMESTAMP;
BEGIN
    -- Execute the query being tested
    WITH
        latest_user_record AS (
            SELECT
                login,
                first_name,
                last_name,
                id_code,
                display_name,
                csa_title,
                csa_email,
                department,
                user_status,
                status,
                active,
                forwarded_chat_popup_notifications,
                forwarded_chat_sound_notifications,
                forwarded_chat_email_notifications,
                new_chat_popup_notifications,
                new_chat_sound_notifications,
                new_chat_email_notifications,
                use_autocorrect
            FROM temp_denorm_table
            WHERE id_code = test_id_code
            ORDER BY id DESC
            LIMIT 1
        )
    INSERT INTO temp_denorm_table (
        login,
        first_name,
        last_name,
        id_code,
        display_name,
        csa_title,
        csa_email,
        department,
        authority_name,
        user_status,
        status,
        active,
        forwarded_chat_popup_notifications,
        forwarded_chat_sound_notifications,
        forwarded_chat_email_notifications,
        new_chat_popup_notifications,
        new_chat_sound_notifications,
        new_chat_email_notifications,
        use_autocorrect,
        created
    )
    SELECT
        login,
        first_name,
        last_name,
        id_code,
        display_name,
        csa_title,
        csa_email,
        department,
        new_roles,
        user_status,
        status,
        active,
        forwarded_chat_popup_notifications,
        forwarded_chat_sound_notifications,
        forwarded_chat_email_notifications,
        new_chat_popup_notifications,
        new_chat_sound_notifications,
        new_chat_email_notifications,
        use_autocorrect,
        test_timestamp
    FROM latest_user_record;
    
    -- Also test the second user
    test_id_code := 'US002';
    new_roles := ARRAY['ROLE_MANAGER', 'ROLE_ADMIN'];
    test_timestamp := CURRENT_TIMESTAMP + INTERVAL '1 minute';
    
    WITH
        latest_user_record AS (
            SELECT
                login,
                first_name,
                last_name,
                id_code,
                display_name,
                csa_title,
                csa_email,
                department,
                user_status,
                status,
                active,
                forwarded_chat_popup_notifications,
                forwarded_chat_sound_notifications,
                forwarded_chat_email_notifications,
                new_chat_popup_notifications,
                new_chat_sound_notifications,
                new_chat_email_notifications,
                use_autocorrect
            FROM temp_denorm_table
            WHERE id_code = test_id_code
            ORDER BY id DESC
            LIMIT 1
        )
    INSERT INTO temp_denorm_table (
        login,
        first_name,
        last_name,
        id_code,
        display_name,
        csa_title,
        csa_email,
        department,
        authority_name,
        user_status,
        status,
        active,
        forwarded_chat_popup_notifications,
        forwarded_chat_sound_notifications,
        forwarded_chat_email_notifications,
        new_chat_popup_notifications,
        new_chat_sound_notifications,
        new_chat_email_notifications,
        use_autocorrect,
        created
    )
    SELECT
        login,
        first_name,
        last_name,
        id_code,
        display_name,
        csa_title,
        csa_email,
        department,
        new_roles,
        user_status,
        status,
        active,
        forwarded_chat_popup_notifications,
        forwarded_chat_sound_notifications,
        forwarded_chat_email_notifications,
        new_chat_popup_notifications,
        new_chat_sound_notifications,
        new_chat_email_notifications,
        use_autocorrect,
        test_timestamp
    FROM latest_user_record;
END $$;

-- Display the data after inserts
SELECT 'Data After Inserts:' AS section;
SELECT * FROM temp_denorm_table
ORDER BY id;

-- Verify that the latest records were used for the insert
SELECT 'Verification Tests:' AS section;

-- Test 1: Check if user1's new record uses the latest values (Support Lead) 
-- but with updated roles
WITH
    latest_records AS (
        SELECT
            id,
            id_code,
            authority_name
        FROM temp_denorm_table
        WHERE id_code = 'US001'
        ORDER BY id DESC
        LIMIT 2
    )

SELECT
    'Test 1: User1 updated roles based on latest record' AS test_description,
    CASE
        WHEN (
            (SELECT ARRAY_LENGTH(authority_name, 1) FROM latest_records LIMIT 1 OFFSET 0
            )
            = 3
            AND (SELECT authority_name FROM latest_records LIMIT 1 OFFSET 0)::TEXT [] @> ARRAY['ROLE_USER', 'ROLE_SUPPORT', 'ROLE_ADMIN']::TEXT []
            AND (
                SELECT csa_title FROM temp_denorm_table
                WHERE id = (SELECT id FROM latest_records LIMIT 1 OFFSET 0)
            ) = 'Support Lead'
        ) THEN 'PASS'
        ELSE 'FAIL'
    END AS result;

-- Test 2: Check if user2's new record uses all fields from the previous record
-- but with updated roles
WITH
    latest_records AS (
        SELECT
            id,
            id_code,
            authority_name
        FROM temp_denorm_table
        WHERE id_code = 'US002'
        ORDER BY id DESC
        LIMIT 2
    )

SELECT
    'Test 2: User2 updated roles based on latest record' AS test_description,
    CASE
        WHEN (
            (SELECT ARRAY_LENGTH(authority_name, 1) FROM latest_records LIMIT 1 OFFSET 0
            )
            = 2
            AND (SELECT authority_name FROM latest_records LIMIT 1 OFFSET 0)::TEXT [] @> ARRAY['ROLE_MANAGER', 'ROLE_ADMIN']::TEXT []
            AND (
                SELECT csa_title FROM temp_denorm_table
                WHERE id = (SELECT id FROM latest_records LIMIT 1 OFFSET 0)
            ) = 'Manager'
        ) THEN 'PASS'
        ELSE 'FAIL'
    END AS result;

-- Overall test result
SELECT 'Overall Test Result:' AS section;
WITH
    test_results AS (
        -- Test 1
        SELECT
            COALESCE((
                EXISTS (
                    SELECT 1 FROM temp_denorm_table
                    WHERE
                        id_code = 'US001'
                        AND csa_title = 'Support Lead'
                        AND ARRAY_LENGTH(authority_name, 1) = 3
                        AND authority_name::TEXT []
                        @> ARRAY['ROLE_USER', 'ROLE_SUPPORT', 'ROLE_ADMIN']::TEXT []
                )
            ), FALSE) AS test_1_passed,

            -- Test 2
            COALESCE((
                EXISTS (
                    SELECT 1 FROM temp_denorm_table
                    WHERE
                        id_code = 'US002'
                        AND csa_title = 'Manager'
                        AND ARRAY_LENGTH(authority_name, 1) = 2
                        AND authority_name::TEXT []
                        @> ARRAY['ROLE_MANAGER', 'ROLE_ADMIN']::TEXT []
                )
            ), FALSE) AS test_2_passed
    )

SELECT
    CASE
        WHEN
            test_1_passed AND test_2_passed
            THEN 'PASS: Insert query correctly uses latest record values'
        ELSE 'FAIL: Insert query does not work as expected'
    END AS test_result
FROM test_results;

-- Clean up
DROP TABLE temp_denorm_table;
