declaration:
  call: declare
  version: 0.1
  description: "Decription placeholder for 'USER-PROFILE-SETTINGS'"
  method: get
  accepts: json
  returns: json
  namespace: backoffice
  allowlist:
    headers:
      - field: cookie
        type: string
        description: "Cookie field"

get_user_info:
  call: http.post
  args:
   url: "[#CHATBOT_TIM]/jwt/custom-jwt-userinfo"
   contentType: plaintext
   headers:
    cookie: ${incoming.headers.cookie}
   plaintext: 
      "customJwtCookie"
  result: res
  next: check_user_info_response

check_user_info_response:
  switch:
    - condition: ${200 <= res.response.statusCodeValue && res.response.statusCodeValue < 300}
      next: assignIdCode
  next: return_bad_request

assignIdCode:
  assign:
    idCode: ${res.response.body.idCode}
  next: getUserSettings

getUserSettings:
  call: http.post
  args:
    url: "[#CHATBOT_RESQL]/get-user-profile-settings"
    body:
      userId: ${idCode}
  result: getUserSettingsResult
  next: validateUserSettingsResultExists

validateUserSettingsResultExists:
  switch:
    - condition: "${getUserSettingsResult.response.body.length > 0}"
      next: returnSuccess
  next: return_not_found

returnSuccess:
  return: ${getUserSettingsResult.response.body}
  next: end

return_bad_request:
  return: "error: bad request"
  next: end

return_not_found:
  return: "error: User not found"
  next: end
