getConfigurationValue:
  call: http.post
  args:
    url: "[#CHATBOT_RESQL]/get-configuration"
    body:
      key: "is_bot_active"
  result: res

return_result:
  return: ${res.response.body[0].value}
