declaration:
  call: declare
  version: 0.1
  description: "Decription placeholder for 'WIDGET-CONFIG'"
  method: get
  accepts: json
  returns: json
  namespace: backoffice

getWidgetConfig:
  call: http.post
  args:
    url: "[#CHATBOT_RESQL]/get-widget-config"
  result: res
  next: validate_response

validate_response:
  switch:
    - condition: "${res.response.body.length > 0}"
      next: mapWidgetConfigData
  next: return_not_found

mapWidgetConfigData:
  call: http.post
  args:
    url: "[#CHATBOT_DMAPPER]/hbs/chat-bot/return_widget_config"
    headers:
      type: json
    body:
      configurationArray: ${res.response.body}
  result: formattedData
  next: return_result

return_result:
  return: ${formattedData.response.body}
  next: end

return_not_found:
  return: "error: not found"
  next: end
