declaration:
  call: declare
  version: 0.1
  description: "Decription placeholder for 'END-USER-SESSION-LENGTH'"
  method: post
  accepts: json
  returns: json
  namespace: backoffice
  allowlist:
    body:
      - field: sessionLength
        type: string
        description: "Body field 'sessionLength'"

extractRequestData:
  assign:
    sessionLength: ${incoming.body.sessionLength}

setConfigurationValue:
  call: http.post
  args:
    url: "[#CHATBOT_RESQL]/set-configuration-value"
    body:
      created: ${new Date().toISOString()}
      key: "end_user_session_length"
      value: ${sessionLength}
  result: setConfigurationResult

return_result:
  return: ${setConfigurationResult.response.body}
