extractRequestData:
  assign:
    sessionLength: ${incoming.body.sessionLength}

setConfigurationValue:
  call: http.post
  args:
    url: "[#CHATBOT_RESQL]/set-configuration-value"
    body:
      created: ${new Date().toISOString()}
      key: "end_user_session_length"
      value: ${sessionLength}
  result: setConfigurationResult

return_result:
  return: ${setConfigurationResult.response.body}
