extractRequestData:
  assign:
    organizationMondayWorkingTimeStartISO: ${incoming.body.organizationMondayWorkingTimeStartISO}
    organizationMondayWorkingTimeEndISO: ${incoming.body.organizationMondayWorkingTimeEndISO}
    organizationTuesdayWorkingTimeStartISO: ${incoming.body.organizationTuesdayWorkingTimeStartISO}
    organizationTuesdayWorkingTimeEndISO: ${incoming.body.organizationTuesdayWorkingTimeEndISO}
    organizationWednesdayWorkingTimeStartISO: ${incoming.body.organizationWednesdayWorkingTimeStartISO}
    organizationWednesdayWorkingTimeEndISO: ${incoming.body.organizationWednesdayWorkingTimeEndISO}
    organizationThursdayWorkingTimeStartISO: ${incoming.body.organizationThursdayWorkingTimeStartISO}
    organizationThursdayWorkingTimeEndISO: ${incoming.body.organizationThursdayWorkingTimeEndISO}
    organizationFridayWorkingTimeStartISO: ${incoming.body.organizationFridayWorkingTimeStartISO}
    organizationFridayWorkingTimeEndISO: ${incoming.body.organizationFridayWorkingTimeEndISO}
    organizationSaturdayWorkingTimeStartISO: ${incoming.body.organizationSaturdayWorkingTimeStartISO}
    organizationSaturdayWorkingTimeEndISO: ${incoming.body.organizationSaturdayWorkingTimeEndISO}
    organizationSundayWorkingTimeStartISO: ${incoming.body.organizationSundayWorkingTimeStartISO}
    organizationSundayWorkingTimeEndISO: ${incoming.body.organizationSundayWorkingTimeEndISO}
    organizationAllWeekdaysTimeStartISO: ${incoming.body.organizationAllWeekdaysTimeStartISO}
    organizationAllWeekdaysTimeEndISO: ${incoming.body.organizationAllWeekdaysTimeEndISO}
    organizationWorkingTimeWeekdays: ${incoming.body.organizationWorkingTimeWeekdays}
    organizationClosedOnWeekEnds: ${incoming.body.organizationClosedOnWeekEnds}
    organizationTheSameOnAllWorkingDays: ${incoming.body.organizationTheSameOnAllWorkingDays}
    organizationWorkingTimeNationalHolidays: ${incoming.body.organizationWorkingTimeNationalHolidays}

setOrganizationWorkingTime:
  call: http.post
  args:
    url: "[#CHATBOT_RESQL]/set-organization-working-time"
    body:
      organizationMondayWorkingTimeStartISO: ${organizationMondayWorkingTimeStartISO}
      organizationMondayWorkingTimeEndISO: ${organizationMondayWorkingTimeEndISO}
      organizationTuesdayWorkingTimeStartISO: ${organizationTuesdayWorkingTimeStartISO}
      organizationTuesdayWorkingTimeEndISO: ${organizationTuesdayWorkingTimeEndISO}
      organizationWednesdayWorkingTimeStartISO: ${organizationWednesdayWorkingTimeStartISO}
      organizationWednesdayWorkingTimeEndISO: ${organizationWednesdayWorkingTimeEndISO}
      organizationThursdayWorkingTimeStartISO: ${organizationThursdayWorkingTimeStartISO}
      organizationThursdayWorkingTimeEndISO: ${organizationThursdayWorkingTimeEndISO}
      organizationFridayWorkingTimeStartISO: ${organizationFridayWorkingTimeStartISO}
      organizationFridayWorkingTimeEndISO: ${organizationFridayWorkingTimeEndISO}
      organizationSaturdayWorkingTimeStartISO: ${organizationSaturdayWorkingTimeStartISO}
      organizationSaturdayWorkingTimeEndISO: ${organizationSaturdayWorkingTimeEndISO}
      organizationSundayWorkingTimeStartISO: ${organizationSundayWorkingTimeStartISO}
      organizationSundayWorkingTimeEndISO: ${organizationSundayWorkingTimeEndISO}
      organizationAllWeekdaysTimeStartISO: ${organizationAllWeekdaysTimeStartISO}
      organizationAllWeekdaysTimeEndISO: ${organizationAllWeekdaysTimeEndISO}
      organizationWorkingTimeWeekdays: ${organizationWorkingTimeWeekdays}
      organizationClosedOnWeekEnds: ${organizationClosedOnWeekEnds}
      organizationTheSameOnAllWorkingDays: ${organizationTheSameOnAllWorkingDays}
      organizationWorkingTimeNationalHolidays: ${organizationWorkingTimeNationalHolidays}
      created: ${new Date().toISOString()}
  result: setOrganizationWorkingTimeResult

mapOrganizationWorkingTimeData:
  call: http.post
  args:
    url: "[#CHATBOT_DMAPPER]/hbs/chat-bot/return_organization_working_time"
    headers:
      type: json
    body:
      configurationArray: ${setOrganizationWorkingTimeResult.response.body}
  result: organizationWorkingTimeData

return_result:
  return: ${organizationWorkingTimeData.response.body}
  next: end
