declaration:
  call: declare
  version: 0.1
  description: "Decription placeholder for 'WIDGET-CONFIG'"
  method: post
  accepts: json
  returns: json
  namespace: backoffice
  allowlist:
    body:
      - field: isAuthConversations
        type: boolean
        description: "Body field 'isAuthConversations'"
      - field: isAnonymConversations
        type: boolean
        description: "Body field 'isAnonymConversations'"
      - field: authPeriod
        type: string
        description: "Body field 'authPeriod'"
      - field: anonymPeriod
        type: string
        description: "Body field 'anonymPeriod'"
      - field: deletionTimeISO
        type: string
        description: "Body field 'deletionTimeISO'"

extractRequestData:
  assign:
    isAuthConversations: ${incoming.body.isAuthConversations}
    isAnonymConversations: ${incoming.body.isAnonymConversations}
    authPeriod: ${incoming.body.authPeriod}
    anonymPeriod: ${incoming.body.anonymPeriod}
    deletionTimeISO: ${incoming.body.deletionTimeISO}

setConfig:
  call: http.post
  args:
    url: "[#CHATBOT_RESQL]/update-conversation-delete-settings"
    body:
      isAuthConversations: ${isAuthConversations}
      isAnonymConversations: ${isAnonymConversations}
      authPeriod: ${authPeriod}
      anonymPeriod: ${anonymPeriod}
      deletionTimeISO: ${deletionTimeISO}
      created: ${new Date().toISOString()}
  result: res

return_result:
  return: ${res.response.body}
  next: end
