name: Run checks
on:
  push:
    branches: [main, dev]
    paths:
      - 'notification-server/**'
  pull_request:
    types: [opened, ready_for_review, reopened, synchronize]
    paths:
      - 'notification-server/**'
concurrency:
  group: ${{ github.ref }}-checks-notification-server
  cancel-in-progress: true

jobs:
  format:
    uses: ./.github/workflows/run-check.yml
    with:
      command: npm run format
  lint:
    uses: ./.github/workflows/run-check.yml
    with:
      command: npm run lint
  test:
    uses: ./.github/workflows/run-check.yml
    with:
      command: npm run test:run
