name: Run check
on:
  workflow_call:
    inputs:
      command:
        required: true
        type: string

jobs:
  check:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: 'notification-server/package.json'
          cache: npm
          cache-dependency-path: 'notification-server/package-lock.json'
      - run: npm ci
        working-directory: notification-server
      - run: ${{ inputs.command }}
        working-directory: notification-server
