extractRequestData:
  assign:
    sessionLength: ${incoming.body.sessionLength}
  next: setConfigurationValue

setConfigurationValue:
  call: http.post
  args:
    url: "[#CHATBOT_BYK_RESQL]:[#CHATBOT_BYK_RESQL_PORT]/set-configuration-value"
    body:
      created: ${new Date().toISOString()}
      key: "end_user_session_length"
      value: ${sessionLength}
  result: setConfigurationResult
  next: returnSuccess

returnSuccess:
  return: ${setConfigurationResult.response.body}
  next: end
