declaration:
  call: declare
  version: 0.1
  description: "Decription placeholder for 'SKM-CONFIG'"
  method: get
  accepts: json
  returns: json
  namespace: backoffice

getSkmConfig:
  call: http.post
  args:
    url: "[#CHATBOT_RESQL]/get-skm-config"
  result: res

return_result:
  return: ${res.response.body[0]}
