name: Build and publish Buerokratt-Chatbot in dev

on:
  push:
    branches:
      - dev
    paths:
      - '.env' 

jobs:
  PackageDeploy:
    runs-on: ubuntu-22.04

    steps:
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

      - name: Install termcolor on the remote server
        run: |
          ssh ubuntu@${{ secrets.SERVER_IP }} 'cd /opt/etapp2/uptodate/PIPELINE && python3 -m pip install termcolor'

      - name: Install colorama on the remote server
        run: |
          ssh ubuntu@${{ secrets.SERVER_IP }} 'cd /opt/etapp2/uptodate/PIPELINE && python3 -m pip install colorama'


      - name: Setup and run containers
        id: setup-and-run-containers
        run: |
          ssh ubuntu@${{ secrets.SERVER_IP }} 'cd /opt/etapp2/uptodate/PIPELINE && python3 byk-chat.py'
