name: Run checks
on:
  push:
    branches: [main, dev]
    paths:
      - "GUI/**"
      - "notification-server/**"
      - ".github/**"
  pull_request:
    types: [opened, ready_for_review, reopened, synchronize]
    paths:
      - "GUI/**"
      - "notification-server/**"
      - ".github/**"
concurrency:
  group: ${{ github.ref }}-checks
  cancel-in-progress: true

jobs:
  frontend-format:
    uses: ./.github/workflows/run-check.yml
    with:
      working_directory: GUI
      command: npm run format

  frontend-lint:
    uses: ./.github/workflows/run-check.yml
    with:
      working_directory: GUI
      command: npm run lint

  frontend-test:
    uses: ./.github/workflows/run-check.yml
    with:
      working_directory: GUI
      command: npm run test:run

  frontend-typecheck:
    uses: ./.github/workflows/run-check.yml
    with:
      working_directory: GUI
      command: npm run typecheck

  frontend-build:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - run: cd GUI && docker image build .

  notification-server-format:
    uses: ./.github/workflows/run-check.yml
    with:
      working_directory: notification-server
      command: npm run format

  notification-server-lint:
    uses: ./.github/workflows/run-check.yml
    with:
      working_directory: notification-server
      command: npm run lint

  notification-server-test:
    uses: ./.github/workflows/run-check.yml
    with:
      working_directory: notification-server
      command: npm run test:run
